import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes, TextareaHTMLAttributes } from 'react'
import { cva } from 'class-variance-authority'
import { clsx } from 'clsx'
import { twMerge } from 'tailwind-merge'
function cn(...values: Parameters<typeof clsx>) { return twMerge(clsx(values)) }
const buttonStyles = cva('inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-colors disabled:cursor-not-allowed disabled:opacity-55', { variants: { variant: { primary: 'bg-[var(--color-primary)] text-white hover:bg-[var(--color-primary-hover)]', secondary: 'border border-[var(--color-border)] bg-white text-[var(--color-text-primary)] hover:bg-[var(--color-surface-muted)]', ghost: 'text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-muted)]' } }, defaultVariants: { variant: 'primary' } })
/** Renders a consistent action control. */ export function Button({className,variant,...props}: ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'}) { return <button className={cn(buttonStyles({variant}),className)} {...props} /> }
/** Renders a compact text input. */ export function Input({className,...props}: InputHTMLAttributes<HTMLInputElement>) { return <input className={cn('w-full rounded-lg border border-[var(--color-border)] bg-white px-3 py-2 text-sm placeholder:text-[var(--color-text-secondary)]',className)} {...props} /> }
/** Renders a compact multiline input. */ export function Textarea({className,...props}: TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className={cn('w-full rounded-lg border border-[var(--color-border)] bg-white px-3 py-2 text-sm placeholder:text-[var(--color-text-secondary)]',className)} {...props} /> }
/** Renders a compact native select control. */ export function Select({className,...props}: SelectHTMLAttributes<HTMLSelectElement>) { return <select className={cn('w-full rounded-lg border border-[var(--color-border)] bg-white px-3 py-2 text-sm',className)} {...props} /> }
/** Groups a labelled control with an optional supporting message. */ export function Field({label,children,message}:{label:string;children:ReactNode;message?:string}) { return <label className="grid gap-1.5 text-sm font-medium">{label}{children}{message?<span className="text-xs font-normal text-[var(--color-text-secondary)]">{message}</span>:null}</label> }
/** Displays a contained informational or error message. */ export function InlineNotice({children,tone='info'}:{children:ReactNode;tone?:'info'|'error'}) { return <div role={tone==='error'?'alert':'status'} className={cn('rounded-lg border px-4 py-3 text-sm',tone==='error'?'border-red-200 bg-[var(--color-error-surface)] text-[var(--color-error)]':'border-blue-200 bg-blue-50 text-blue-800')}>{children}</div> }
