export type KnowledgeDocumentType='official_document'|'runbook'|'maintenance_guide'|'incident'|'operator_journal'
export type KnowledgeAuthority='official'|'internal_approved'|'operator_authored'
export interface ServiceTag { service_id:string; aliases:string[]; supported_versions:string[] }
export interface KnowledgeVersion { version:number; title:string; document_type:KnowledgeDocumentType; authority:KnowledgeAuthority; owner:string; source_reference:string|null; media_type:string; content_hash:string; extraction_state:'pending'|'ready'|'failed'; lifecycle_state:'imported'|'approved'|'deprecated'; service_tags:ServiceTag[] }
export interface KnowledgeDocument { id:string; title:string; document_type:KnowledgeDocumentType; authority:KnowledgeAuthority; service_tags:ServiceTag[]; active_version:number|null; versions?:KnowledgeVersion[] }
export interface KnowledgeChunk { ordinal:number; location:string; text:string }
export class KnowledgeApiError extends Error { readonly status:number; constructor(status:number,message:string){super(message);this.status=status} }
const base='/api/v1/knowledge'
async function request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${base}${path}`,init);if(!response.ok){let message='Knowledge request failed.';try{message=(await response.json() as {message?:string}).message??message}catch{/* safe generic message */}throw new KnowledgeApiError(response.status,message)}return response.json() as Promise<T>}
/** Lists manually managed knowledge documents. */ export function listKnowledgeDocuments(signal?:AbortSignal){return request<KnowledgeDocument[]>('/documents',{signal})}
/** Loads one immutable document history. */ export function getKnowledgeDocument(id:string,signal?:AbortSignal){return request<KnowledgeDocument>(`/documents/${encodeURIComponent(id)}`,{signal})}
/** Loads one exact historical chunk for a recognized curated citation. */ export function getKnowledgeChunk(id:string,version:number,ordinal:number,signal?:AbortSignal){return request<KnowledgeChunk>(`/documents/${encodeURIComponent(id)}/versions/${version}/chunks/${ordinal}`,{signal})}
/** Uploads a new knowledge document with explicit source metadata. */ export function uploadKnowledgeDocument(file:File,metadata:Omit<KnowledgeVersion,'version'|'media_type'|'content_hash'|'extraction_state'|'lifecycle_state'>){const body=new FormData();body.append('file',file);body.append('metadata',JSON.stringify(metadata));return request<KnowledgeDocument>('/documents',{method:'POST',body})}
/** Runs an explicit retained-source extraction retry. */ export function retryExtraction(id:string,version:number){return request<KnowledgeDocument>(`/documents/${encodeURIComponent(id)}/versions/${version}/retry-extraction`,{method:'POST'})}
/** Publishes a ready immutable version for retrieval after explicit disclosure confirmation. */ export function approveVersion(id:string,version:number){if(!window.confirm(`Approve version ${version}? Extracted approved document text and later bounded finding-grounded retrieval queries are sent to OpenRouter for embedding. Original file bytes, raw telemetry, and provider payloads are not.`))return Promise.reject(new KnowledgeApiError(0,'Approval was not confirmed.'));return request<KnowledgeDocument>(`/documents/${encodeURIComponent(id)}/versions/${version}/approve`,{method:'POST'})}
/** Removes one approved version from retrieval eligibility. */ export function deprecateVersion(id:string,version:number){return request<KnowledgeDocument>(`/documents/${encodeURIComponent(id)}/versions/${version}/deprecate`,{method:'POST'})}
export function sourceDownloadHref(id:string,version:number){return `${base}/documents/${encodeURIComponent(id)}/versions/${version}/source`}
