import { CheckCircle2, FileDown, FilePlus2, FileUp, Plus, RefreshCw, X } from 'lucide-react'
import { useCallback, useEffect, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Button, Field, InlineNotice, Input, PageHeader, Select } from '../../components/ui'
import { approveVersion, deprecateVersion, getKnowledgeChunk, getKnowledgeDocument, listKnowledgeDocuments, parseCuratedLocator, retryExtraction, sourceDownloadHref, uploadKnowledgeDocument, type KnowledgeDocument, type KnowledgeUploadMetadata, type KnowledgeVersion } from './api'

type ChunkState = { location: string; text: string } | null

/** Manages the trusted-MVP corpus without document editing or external synchronization. */
export function KnowledgePage() {
  const [params, setParams] = useSearchParams(); const [documents, setDocuments] = useState<KnowledgeDocument[]>([]); const [selected, setSelected] = useState<KnowledgeDocument | null>(null); const [chunk, setChunk] = useState<ChunkState>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const sequence = useRef(0); const active = useRef<AbortController | null>(null); const documentId = params.get('document'); const version = Number(params.get('version')); const reference = params.get('reference') ?? ''
  const load = useCallback(async () => { active.current?.abort(); const controller = new AbortController(); const request = ++sequence.current; const locator = parseCuratedLocator(reference); active.current = controller; setLoading(true); setError(''); try { const listed = await listKnowledgeDocuments(controller.signal); let detail: KnowledgeDocument | null = null; let referencedChunk: ChunkState = null; if (documentId) { detail = await getKnowledgeDocument(documentId, controller.signal); if (Number.isSafeInteger(version) && version > 0 && locator) referencedChunk = await getKnowledgeChunk(documentId, version, locator, controller.signal) } if (controller.signal.aborted || sequence.current !== request) return; setDocuments(listed); setSelected(detail); setChunk(referencedChunk) } catch { if (!controller.signal.aborted && sequence.current === request) setError('Knowledge Administration is unavailable. Try again.') } finally { if (sequence.current === request) { active.current = null; setLoading(false) } } }, [documentId, reference, version])
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => { window.clearTimeout(timer); active.current?.abort() } }, [load])
  const select = (id: string) => setParams({ document: id })
  const apply = async (action: (id: string, itemVersion: number) => Promise<KnowledgeDocument>, item: KnowledgeVersion) => { if (!selected) return; try { await action(selected.id, item.version); await load() } catch { setError('The lifecycle action could not be completed. Try again.') } }
  const afterUpload = (document: KnowledgeDocument) => { setParams({ document: document.id }) }
  return <section className="mx-auto max-w-6xl"><PageHeader eyebrow="Knowledge" title="Knowledge Administration" description="Manual PDF and Markdown sources for curated retrieval. Knowledge is not Observation evidence." /><div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(20rem,0.9fr)]"><div className="space-y-5"><UploadForm onCreated={afterUpload}/>{error ? <InlineNotice tone="error">{error}</InlineNotice> : null}<section className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">Documents</h2><Button variant="secondary" onClick={() => void load()}>Refresh</Button></div>{loading ? <p className="mt-4 text-sm text-[var(--color-text-secondary)]">Loading knowledge documents…</p> : documents.length ? <ul className="mt-4 space-y-2">{documents.map((document) => <li key={document.id}><button type="button" onClick={() => select(document.id)} className="w-full rounded-lg border border-[var(--color-border)] p-3 text-left hover:bg-[var(--color-surface-muted)]"><p className="font-medium">{document.title}</p><p className="mt-1 text-sm text-[var(--color-text-secondary)]">{document.document_type.replaceAll('_', ' ')} · {document.authority.replaceAll('_', ' ')} · active version {document.active_version ?? 'none'}</p><p className="mt-1 text-xs text-[var(--color-warning)]">Knowledge material · {document.service_tags.map((tag) => tag.service_id).join(', ') || 'globally applicable'}</p></button></li>)}</ul> : <p className="mt-4 text-sm text-[var(--color-text-secondary)]">No manual knowledge documents have been uploaded.</p>}</section></div><section className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5">{selected ? <DocumentDetail document={selected} chunk={chunk} onAction={apply} onUploaded={afterUpload} /> : <p className="text-sm text-[var(--color-text-secondary)]">Select a document to inspect immutable versions, source metadata, and lifecycle state.</p>}</section></div></section>
}

function UploadForm({ documentId, onCreated }: { documentId?: string; onCreated: (document: KnowledgeDocument) => void }) {
  const [file, setFile] = useState<File | null>(null); const [title, setTitle] = useState(''); const [owner, setOwner] = useState(''); const [sourceReference, setSourceReference] = useState(''); const [type, setType] = useState<KnowledgeVersion['document_type']>('runbook'); const [authority, setAuthority] = useState<KnowledgeVersion['authority']>('internal_approved'); const [tags, setTags] = useState<ServiceTagDraft[]>([]); const [pending, setPending] = useState(false); const [error, setError] = useState('')
  const updateTag = (index: number, value: Partial<ServiceTagDraft>) => setTags((current) => current.map((tag, tagIndex) => tagIndex === index ? { ...tag, ...value } : tag))
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!file || !title.trim() || !owner.trim()) { setError('Choose a PDF or Markdown file and complete the required metadata.'); return } if (!/\.(pdf|md)$/i.test(file.name)) { setError('Only PDF and Markdown files are accepted.'); return } const populatedTags = tags.filter((tag) => tag.serviceId.trim() || tag.aliases.trim() || tag.supportedVersions.trim()); if (populatedTags.some((tag) => !tag.serviceId.trim())) { setError('Enter a service ID for every populated service applicability tag.'); return } const metadata: KnowledgeUploadMetadata = { title: title.trim(), document_type: type, authority, owner: owner.trim(), source_reference: sourceReference.trim() || null, service_tags: populatedTags.map((tag) => ({ service_id: tag.serviceId.trim(), aliases: commaValues(tag.aliases), supported_versions: commaValues(tag.supportedVersions) })) }; setPending(true); setError(''); try { onCreated(await uploadKnowledgeDocument(file, metadata, documentId)) } catch { setError('The document could not be uploaded. Check the file and metadata, then try again.') } finally { setPending(false) } }
  return <form onSubmit={submit} className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5"><h2 className="font-semibold">{documentId ? 'Upload later immutable version' : 'Upload knowledge document'}</h2><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Manual upload only. The original source is retained before extraction; it is never edited in this application.</p>{error ? <div className="mt-3"><InlineNotice tone="error">{error}</InlineNotice></div> : null}<div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Source file"><Input type="file" accept="application/pdf,text/markdown,.pdf,.md" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></Field><Field label="Title"><Input value={title} onChange={(event) => setTitle(event.target.value)} /></Field><Field label="Document type"><Select value={type} onChange={(event) => setType(event.target.value as KnowledgeVersion['document_type'])}>{['official_document', 'runbook', 'maintenance_guide', 'incident', 'operator_journal'].map((value) => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</Select></Field><Field label="Authority"><Select value={authority} onChange={(event) => setAuthority(event.target.value as KnowledgeVersion['authority'])}>{['official', 'internal_approved', 'operator_authored'].map((value) => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</Select></Field><Field label="Owner"><Input value={owner} onChange={(event) => setOwner(event.target.value)} /></Field><Field label="Source reference (optional)"><Input value={sourceReference} onChange={(event) => setSourceReference(event.target.value)} /></Field></div><div className="mt-5 space-y-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-medium">Service applicability (optional)</h3><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Add every service tag that this immutable source version supports.</p></div><Button type="button" variant="secondary" onClick={() => setTags((current) => [...current, blankServiceTag()])}><Plus size={16} aria-hidden="true" />Add service applicability</Button></div>{tags.map((tag, index) => <ServiceTagFields key={tag.key} index={index} tag={tag} onChange={updateTag} onRemove={() => setTags((current) => current.filter((item) => item.key !== tag.key))} />)}</div><Button className="mt-4" disabled={pending}><FileUp size={17} aria-hidden="true" />{pending ? 'Uploading…' : documentId ? 'Upload later version' : 'Upload document'}</Button></form>
}

type ServiceTagDraft = { key: number; serviceId: string; aliases: string; supportedVersions: string }
let nextServiceTagKey = 0
function blankServiceTag(): ServiceTagDraft { return { key: nextServiceTagKey++, serviceId: '', aliases: '', supportedVersions: '' } }
function ServiceTagFields({ index, tag, onChange, onRemove }: { index: number; tag: ServiceTagDraft; onChange: (index: number, value: Partial<ServiceTagDraft>) => void; onRemove: () => void }) {
  const number = index + 1
  return <fieldset className="rounded-lg border border-[var(--color-border)] p-4"><legend className="px-1 text-sm font-medium">Service applicability {number}</legend><div className="grid gap-4 sm:grid-cols-2"><Field label={`Service ID ${number}`}><Input value={tag.serviceId} onChange={(event) => onChange(index, { serviceId: event.target.value })} placeholder="mprm-server" /></Field><Field label={`Service aliases ${number} (optional)`} description="Comma-separated."><Input value={tag.aliases} onChange={(event) => onChange(index, { aliases: event.target.value })} /></Field><Field label={`Supported versions ${number} (optional)`} description="Comma-separated opaque labels."><Input value={tag.supportedVersions} onChange={(event) => onChange(index, { supportedVersions: event.target.value })} placeholder="2.x, 3.x" /></Field></div><Button type="button" variant="ghost" className="mt-3" onClick={onRemove}><X size={16} aria-hidden="true" />Remove service applicability {number}</Button></fieldset>
}

function DocumentDetail({ document, chunk, onAction, onUploaded }: { document: KnowledgeDocument; chunk: ChunkState; onAction: (action: (id: string, version: number) => Promise<KnowledgeDocument>, item: KnowledgeVersion) => void; onUploaded: (document: KnowledgeDocument) => void }) {
  const [showVersionUpload, setShowVersionUpload] = useState(false); const versions = document.versions ?? []
  const approve = (item: KnowledgeVersion) => { if (window.confirm(`Approve version ${item.version}? Extracted approved document text and later bounded finding-grounded retrieval queries are sent to OpenRouter for embedding. Original file bytes, raw telemetry, and provider payloads are not.`)) void onAction(approveVersion, item) }
  const deprecate = (item: KnowledgeVersion) => { if (window.confirm(`Deprecate version ${item.version}? It will no longer be eligible for retrieval, but its retained source and history remain available.`)) void onAction(deprecateVersion, item) }
  return <><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{document.title}</h2><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Immutable version history. Source files download as attachments.</p></div><Button type="button" variant="secondary" onClick={() => setShowVersionUpload((shown) => !shown)}><FilePlus2 size={16} aria-hidden="true" />Upload later version</Button></div>{showVersionUpload ? <div className="mt-4"><UploadForm documentId={document.id} onCreated={onUploaded}/></div> : null}{chunk ? <section className="mt-4 rounded-lg border border-[var(--color-warning-border)] bg-[var(--color-warning-surface)] p-4"><h3 className="font-semibold">Referenced knowledge passage</h3><p className="mt-2 text-sm">{chunk.location}</p><pre className="mt-3 whitespace-pre-wrap text-sm">{chunk.text}</pre></section> : null}<ul className="mt-5 space-y-3">{versions.map((item) => <li key={item.version} className="rounded-lg border border-[var(--color-border)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-medium">Version {item.version} · {item.lifecycle_state}</h3><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Extraction: {item.extraction_state} · {item.media_type}</p><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Owner: {item.owner} · Type: {item.document_type.replaceAll('_', ' ')} · Authority: {item.authority.replaceAll('_', ' ')}</p><p className="mt-1 break-words text-sm text-[var(--color-text-secondary)]">Source reference: {item.source_reference ?? 'none supplied'}</p><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Services: {formatTags(item.service_tags)}</p><p className="mt-1 break-all text-xs text-[var(--color-text-secondary)]">Hash: {item.content_hash}</p></div><a className="inline-flex items-center gap-1 text-sm text-[var(--color-primary)] underline" href={sourceDownloadHref(document.id, item.version)}><FileDown size={15} aria-hidden="true" />Download source</a></div><div className="mt-3 flex flex-wrap gap-2">{item.extraction_state === 'failed' ? <Button variant="secondary" onClick={() => void onAction(retryExtraction, item)}><RefreshCw size={16} aria-hidden="true" />Retry extraction</Button> : null}{item.lifecycle_state === 'imported' && item.extraction_state === 'ready' ? <Button onClick={() => approve(item)}><CheckCircle2 size={16} aria-hidden="true" />Approve version</Button> : null}{item.lifecycle_state === 'approved' ? <Button variant="secondary" onClick={() => deprecate(item)}>Deprecate version</Button> : null}</div></li>)}</ul>{!versions.length ? <p className="mt-4 text-sm text-[var(--color-text-secondary)]">No version history is available.</p> : null}</>
}
function commaValues(value: string) { return value.split(',').map((item) => item.trim()).filter(Boolean) }
function formatTags(tags: KnowledgeVersion['service_tags']) { return tags.length ? tags.map((tag) => `${tag.service_id}${tag.aliases.length ? ` (aliases: ${tag.aliases.join(', ')})` : ''}${tag.supported_versions.length ? ` (versions: ${tag.supported_versions.join(', ')})` : ''}`).join('; ') : 'Globally applicable' }
