import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { KnowledgePage } from './KnowledgePage'

afterEach(()=>vi.unstubAllGlobals())
describe('KnowledgePage',()=>{
  it('offers only manual PDF or Markdown upload and no external-sync, editor, or role controls',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify([]))));render(<MemoryRouter><KnowledgePage/></MemoryRouter>);expect(await screen.findByText('Upload knowledge document')).toBeTruthy();const file=screen.getByLabelText('Source file') as HTMLInputElement;expect(file.accept).toContain('application/pdf');expect(file.accept).toContain('text/markdown');expect(screen.queryByText(/Confluence|sync|editor|role/i)).toBeNull()})
  it('shows immutable historical metadata and permits a later version upload without replacing it',async()=>{const document={id:'123e4567-e89b-12d3-a456-426614174000',title:'Cooling runbook',document_type:'runbook',authority:'official',service_tags:[{service_id:'cooling',aliases:['chiller'],supported_versions:['2.x']}],active_version:2,versions:[{version:1,title:'Cooling runbook',document_type:'runbook',authority:'official',owner:'Operations',source_reference:'DOC-1',media_type:'application/pdf',content_hash:'old-hash',extraction_state:'ready',lifecycle_state:'deprecated',service_tags:[]},{version:2,title:'Cooling runbook',document_type:'runbook',authority:'official',owner:'Operations',source_reference:'DOC-2',media_type:'text/markdown',content_hash:'new-hash',extraction_state:'ready',lifecycle_state:'approved',service_tags:[{service_id:'cooling',aliases:['chiller'],supported_versions:['2.x']}]}]};const fetchMock=vi.fn((url:string)=>Promise.resolve(new Response(JSON.stringify(url.endsWith('/documents')?[document]:document))));vi.stubGlobal('fetch',fetchMock);render(<MemoryRouter initialEntries={['/knowledge?document=123e4567-e89b-12d3-a456-426614174000&version=1&reference=pdf%3Apage%3A7%3Achunk%3A2']}><KnowledgePage/></MemoryRouter>);expect(await screen.findByText('Version 1 · deprecated')).toBeTruthy();expect(screen.getAllByText(/Owner: Operations/)[0]).toBeTruthy();expect(screen.getByText(/Source reference: DOC-1/)).toBeTruthy();expect(screen.getAllByRole('link',{name:'Download source'})[0].getAttribute('href')).toContain('/versions/1/source');await userEvent.click(screen.getByRole('button',{name:'Upload later version'}));expect(screen.getByText('Upload later immutable version')).toBeTruthy();expect(screen.getAllByLabelText('Service aliases (optional)').length).toBe(2);expect(screen.getAllByLabelText('Supported versions (optional)').length).toBe(2)})
})
