import { ApiError, type ApiErrorEnvelope, type DefinitionCapabilities, type KnowledgeScopeSuggestionRequest, type KnowledgeScopeSuggestionResponse, type MetricPreflightResponse, type ObservationCreate, type ObservationResponse, type ObservationSummary } from './types'
const baseUrl='/api/v1'
async function request<T>(path:string,signal?:AbortSignal):Promise<T> { const response=await fetch(`${baseUrl}${path}`,{signal}); if(!response.ok) { let payload:ApiErrorEnvelope|undefined; try { payload=await response.json() as ApiErrorEnvelope } catch { /* generic error */ } throw new ApiError(response.status,payload?.code??'request_failed',payload?.message??`Request failed (${response.status}).`,payload?.field) } return response.json() as Promise<T> }
/** Retrieves compact Observation definitions. */ export function listObservations(signal?:AbortSignal) { return request<ObservationSummary[]>('/observations',signal) }
/** Retrieves one complete, read-only Observation definition. */ export function getObservation(id:string,signal?:AbortSignal) { return request<ObservationResponse>(`/observations/${encodeURIComponent(id)}`,signal) }
/** Retrieves the currently configured Metric adapter/source choices. */ export function getDefinitionCapabilities(signal?:AbortSignal) { return request<DefinitionCapabilities>('/observation-definition-capabilities',signal) }
/** Validates one exact provider-native query without changing an Observation draft. */
export async function preflightMetricQuery(sourceId:string,query:string,signal?:AbortSignal):Promise<MetricPreflightResponse> { const response=await fetch(`${baseUrl}/observation-lens-validations/metric`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source_id:sourceId,query,validation_window:{duration:'15m'}}),signal});if(!response.ok){let error:ApiErrorEnvelope|undefined;try{error=await response.json() as ApiErrorEnvelope}catch{/* generic error */}throw new ApiError(response.status,error?.code??'request_failed',error?.message??`Request failed (${response.status}).`,error?.field)}return response.json() as Promise<MetricPreflightResponse> }
/** Creates one complete Observation Definition aggregate. */ export async function createObservation(payload:ObservationCreate):Promise<ObservationResponse> { const response=await fetch(`${baseUrl}/observations`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok){let error:ApiErrorEnvelope|undefined;try{error=await response.json() as ApiErrorEnvelope}catch{/* generic error */}throw new ApiError(response.status,error?.code??'request_failed',error?.message??`Request failed (${response.status}).`,error?.field)}return response.json() as Promise<ObservationResponse> }
/** Replaces the mutable snapshot of one Observation Definition aggregate. */
export async function updateObservation(id:string,payload:ObservationCreate):Promise<ObservationResponse> { const response=await fetch(`${baseUrl}/observations/${encodeURIComponent(id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok){let error:ApiErrorEnvelope|undefined;try{error=await response.json() as ApiErrorEnvelope}catch{/* generic error */}throw new ApiError(response.status,error?.code??'request_failed',error?.message??`Request failed (${response.status}).`,error?.field)}return response.json() as Promise<ObservationResponse> }
/** Requests a transient, catalog-backed knowledge scope suggestion. */
export async function suggestKnowledgeScope(payload:KnowledgeScopeSuggestionRequest,signal?:AbortSignal):Promise<KnowledgeScopeSuggestionResponse> { const response=await fetch(`${baseUrl}/knowledge/scope-suggestion`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal});if(!response.ok){let error:ApiErrorEnvelope|undefined;try{error=await response.json() as ApiErrorEnvelope}catch{/* generic error */}throw new ApiError(response.status,error?.code??'request_failed',error?.message??'No knowledge scope suggestion is available.')}return response.json() as Promise<KnowledgeScopeSuggestionResponse> }
