import type { ObservationResponse, SemanticDescriptor } from './types'
import type { DraftErrors, ObservationDraft } from './draft'
import type { ReactNode } from 'react'

type ReviewDefinition=Pick<ObservationDraft,'name'|'description'|'objective'|'lenses'|'alert_lenses'|'relationships'>

/** Renders a read-only, ordered configuration review without changing the draft. */
export function DefinitionReview({definition,errors}:{definition:ReviewDefinition;errors?:DraftErrors}) {
  const remaining=errors?Object.values(errors):[]
  return <section aria-labelledby="review-heading" className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6">
    <div className="flex flex-wrap items-baseline justify-between gap-2"><div><h2 id="review-heading">Review</h2><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Verify the aggregate that will be submitted with Create Observation.</p></div><p className={remaining.length?'text-sm font-medium text-[var(--color-error)]':'text-sm font-medium text-[var(--color-primary)]'}>{remaining.length?`${remaining.length} item${remaining.length===1?'':'s'} need attention`:'Ready to create'}</p></div>
    {remaining.length?<ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-[var(--color-error)]" aria-label="Remaining required-field feedback">{remaining.map((message,index)=><li key={`${message}-${index}`}>Needs attention: {message}</li>)}</ul>:<p className="mt-3 text-sm text-[var(--color-text-secondary)]">All currently required definition fields are complete.</p>}
    <ReviewGeneral definition={definition}/>
    <ReviewGroup title="Metric lenses" empty="No Metric lenses configured.">{definition.lenses.map((lens,index)=><article key={lens.clientKey} className="definition-review-card"><p className="font-semibold">{index+1}. <strong>{lens.name||'Unnamed Metric Lens'}</strong> <span className="font-normal text-[var(--color-text-secondary)]">· Metric</span></p><DefinitionValue label="ID" value={lens.id||'Not set'}/><DefinitionValue label="Description" value={lens.description??'None'}/><DefinitionValue label="Type / adapter" value={`${lens.type} / ${lens.adapter_type}`}/><DefinitionValue label="Source ID" value={lens.source_id||'Not set'}/><DefinitionValue label="Metric ID" value={lens.metric_id||'Not set'}/><DefinitionValue label="Query" value={lens.query||'Not set'}/><DefinitionValue label="Unit" value={lens.unit||'Not set'}/><DefinitionList label="Analysis objectives" values={lens.analysis_objectives}/><DefinitionList label="Reference periods" values={lens.reference_periods}/></article>)}</ReviewGroup>
    <ReviewGroup title="Alert lenses" empty="No Alert lenses configured.">{definition.alert_lenses.map((lens,index)=><article key={lens.clientKey} className="definition-review-card"><p className="font-semibold">{index+1}. <strong>{lens.name||'Unnamed Alert Lens'}</strong> <span className="font-normal text-[var(--color-text-secondary)]">· Alert</span></p><DefinitionValue label="ID" value={lens.id||'Not set'}/><DefinitionValue label="Description" value={lens.description??'None'}/><DefinitionValue label="Type / source" value={`${lens.type} / ${lens.source}`}/><DefinitionValue label="Selector query" value={lens.selector.query||'Not set'} preserveWhitespace/><DefinitionList label="Analysis objectives" values={lens.analysis_objectives}/><DefinitionList label="Reference periods" values={lens.reference_periods}/></article>)}</ReviewGroup>
    <ReviewGroup title="Relationships" empty="No Relationships configured.">{definition.relationships.map((relationship,index)=><article key={relationship.clientKey} className="definition-review-card"><p className="font-semibold">{index+1}. <strong>{relationship.name||'Unnamed Relationship'}</strong> <span className="font-normal text-[var(--color-text-secondary)]">· Relationship</span></p><DefinitionValue label="ID" value={relationship.id||'Not set'}/><DefinitionValue label="Description" value={relationship.description??'None'}/><DefinitionList label="Participants" values={relationship.participants}/><DescriptorMap title="Conditions" values={relationship.conditions} empty="Always applicable."/><DescriptorMap title="Expected" values={relationship.expected} empty="No expectations configured."/></article>)}</ReviewGroup>
  </section>
}

/** Renders the complete read-only response projection used by inspection and review. */
export function DefinitionInspection({definition}:{definition:ObservationResponse}) {
  return <><section className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6"><h2>Definition metadata</h2><DefinitionValue label="ID" value={definition.id}/><DefinitionValue label="Schema version" value={String(definition.schema_version)}/><DefinitionValue label="Objective" value={definition.objective}/></section><ReviewGroup title="Metric lenses" empty="No Metric lenses configured.">{definition.lenses.map((lens,index)=><article key={lens.id} className="definition-review-card"><p className="font-semibold">{index+1}. <strong>{lens.name}</strong> <span className="font-normal text-[var(--color-text-secondary)]">· Metric</span></p><DefinitionValue label="ID" value={lens.id}/><DefinitionValue label="Description" value={lens.description??'None'}/><DefinitionValue label="Type / adapter" value={`${lens.type} / ${lens.adapter_type}`}/><DefinitionValue label="Source ID" value={lens.source_id}/><DefinitionValue label="Metric ID" value={lens.metric_id}/><DefinitionValue label="Query" value={lens.query}/><DefinitionValue label="Unit" value={lens.unit}/><DefinitionList label="Analysis objectives" values={lens.analysis_objectives}/><DefinitionList label="Reference periods" values={lens.reference_periods}/></article>)}</ReviewGroup><ReviewGroup title="Alert lenses" empty="No Alert lenses configured.">{definition.alert_lenses.map((lens,index)=><article key={lens.id} className="definition-review-card"><p className="font-semibold">{index+1}. <strong>{lens.name}</strong> <span className="font-normal text-[var(--color-text-secondary)]">· Alert</span></p><DefinitionValue label="ID" value={lens.id}/><DefinitionValue label="Description" value={lens.description??'None'}/><DefinitionValue label="Type / source" value={`${lens.type} / ${lens.source}`}/><DefinitionValue label="Selector query" value={lens.selector.query} preserveWhitespace/><DefinitionList label="Analysis objectives" values={lens.analysis_objectives}/><DefinitionList label="Reference periods" values={lens.reference_periods}/></article>)}</ReviewGroup><ReviewGroup title="Relationships" empty="No Relationships configured.">{definition.relationships.map((relationship,index)=><article key={relationship.id} className="definition-review-card"><p className="font-semibold">{index+1}. <strong>{relationship.name}</strong> <span className="font-normal text-[var(--color-text-secondary)]">· Relationship</span></p><DefinitionValue label="ID" value={relationship.id}/><DefinitionValue label="Description" value={relationship.description??'None'}/><DefinitionList label="Participants" values={relationship.participants}/><DescriptorMap title="Conditions" values={relationship.conditions} empty="Always applicable."/><DescriptorMap title="Expected" values={relationship.expected} empty="No expectations configured."/></article>)}</ReviewGroup></>
}

function ReviewGeneral({definition}:{definition:ReviewDefinition}) { return <section className="mt-5 border-t border-[var(--color-border)] pt-4"><h3 className="font-semibold">General</h3><DefinitionValue label="Name" value={definition.name||'Not set'}/><DefinitionValue label="Description" value={definition.description||'None'}/><DefinitionValue label="Objective" value={definition.objective||'Not set'}/></section> }
function ReviewGroup({title,empty,children}:{title:string;empty:string;children:ReactNode[]}) { return <section className="mt-5 border-t border-[var(--color-border)] pt-4"><p className="font-semibold">{title}</p>{children.length?<div className="mt-3 space-y-3">{children}</div>:<p className="mt-2 text-sm text-[var(--color-text-secondary)]">{empty}</p>}</section> }
function DefinitionValue({label,value,preserveWhitespace=false}:{label:string;value:string;preserveWhitespace?:boolean}) { return <p className="mt-2 text-sm"><span className="font-medium">{label}:</span> <span className={preserveWhitespace?'whitespace-pre-wrap':''}>{value}</span></p> }
function DefinitionList({label,values}:{label:string;values:string[]}) { return <div className="mt-2 text-sm"><span className="font-medium">{label}:</span>{values.length?<><span className="sr-only"> {values.join(', ')}</span>{label==='Reference periods'?<p>References: {values.join(', ')}</p>:null}<ol className="ml-5 list-decimal">{values.map((value,index)=><li key={`${value}-${index}`} className="whitespace-pre-wrap">{value}</li>)}</ol></>:<span> None</span>}</div> }
function DescriptorMap({title,values,empty}:{title:string;values:Record<string,SemanticDescriptor>;empty:string}) { const entries=Object.entries(values).sort(([left],[right])=>left.localeCompare(right));return <section className="mt-3 text-sm"><h4 className="font-medium">{title}</h4>{entries.length?<dl className="mt-1 space-y-1">{entries.map(([lens,descriptor])=><div key={lens} className="rounded border border-[var(--color-border)] p-2"><dt className="font-medium">{lens}</dt><dd>{descriptorText(descriptor)}</dd></div>)}</dl>:<p className="text-[var(--color-text-secondary)]">{empty}</p>}</section> }
function descriptorText(descriptor:SemanticDescriptor) { return [descriptor.trend?.direction?`trend.direction: ${descriptor.trend.direction}`:null,descriptor.trend?.rate?`trend.rate: ${descriptor.trend.rate}`:null,descriptor.variability?.state?`variability.state: ${descriptor.variability.state}`:null].filter(Boolean).join(' · ') }
