/* eslint-disable react-refresh/only-export-components */
import { createContext, useCallback, useContext, useEffect, useMemo, useReducer, useRef, useState, type ReactNode } from 'react'
import { getDefinitionCapabilities } from './api'
import type { AlertLensCreate, DefinitionCapabilities, MetricLensCreate, ObservationCreate, RelationshipCreate, SemanticDescriptor } from './types'
export interface DraftAlert extends AlertLensCreate { clientKey:string }
export interface DraftMetric extends MetricLensCreate { clientKey:string }
export interface DraftRelationship extends RelationshipCreate { clientKey:string }
export interface ObservationDraft { name:string; description:string; objective:string; lenses:DraftMetric[]; alert_lenses:DraftAlert[]; relationships:DraftRelationship[] }
export type DraftErrors=Record<string,string>
const blank=():ObservationDraft=>({name:'',description:'',objective:'',lenses:[],alert_lenses:[],relationships:[]})
const MAX_CHILD_ID_LENGTH=255
export type ObservationChildKind='metric'|'alert'|'relationship'
/** Generates one stable, contract-safe ID for an aggregate-owned Observation child. */
export function generateObservationChildId(name:string,kind:ObservationChildKind,siblingIds:readonly string[],generationTimeMilliseconds:number):string {
 const normalized=name.normalize('NFKD').replace(/\p{M}+/gu,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')
 const prefix=/^[a-z]/.test(normalized)?normalized:kind,timestamp=Math.trunc(generationTimeMilliseconds).toString(36).toLowerCase(),used=new Set(siblingIds)
 let discriminator=1
 while(true){const collisionSuffix=discriminator===1?'':`_${discriminator}`,prefixLength=MAX_CHILD_ID_LENGTH-1-timestamp.length-collisionSuffix.length,candidate=`${prefix.slice(0,prefixLength)}_${timestamp}${collisionSuffix}`;if(!used.has(candidate))return candidate;discriminator+=1}
}
type Action={type:'fresh'}|{type:'general';value:Pick<ObservationDraft,'name'|'description'|'objective'>}|{type:'upsert-alert';value:DraftAlert;key:'new'|string}|{type:'upsert-metric';value:DraftMetric;key:'new'|string}|{type:'upsert-relationship';value:DraftRelationship;key:'new'|string}|{type:'clear'}
function replaceAtKey<T extends {clientKey:string}>(items:T[],value:T,key:string):T[] { if(key==='new')return [...items,value];const index=items.findIndex(item=>item.clientKey===key);return index<0?items:items.map((item,i)=>i===index?value:item) }
function reducer(state:ObservationDraft|null,action:Action):ObservationDraft|null { if(action.type==='fresh')return blank();if(action.type==='clear')return null;if(!state)return state;if(action.type==='general')return {...state,...action.value};if(action.type==='upsert-alert')return {...state,alert_lenses:replaceAtKey(state.alert_lenses,action.value,action.key)};if(action.type==='upsert-metric')return {...state,lenses:replaceAtKey(state.lenses,action.value,action.key)};return {...state,relationships:replaceAtKey(state.relationships,action.value,action.key)} }
export function validateAlert(value:DraftAlert,other:DraftAlert[]=[]):DraftErrors { const errors:DraftErrors={};if(!/^[a-z][a-z0-9_-]*$/.test(value.id))errors.id='Use a lowercase identifier.';if(!value.name.trim())errors.name='Name is required.';if(value.description!==null&&!value.description.trim())errors.description='Description cannot be blank.';if(!value.selector.query.trim())errors.query='Selector query is required.';if(other.some(item=>item.clientKey!==value.clientKey&&item.id===value.id))errors.id='Alert Lens ID must be unique.';if(value.analysis_objectives.some(item=>!item.trim())||new Set(value.analysis_objectives).size!==value.analysis_objectives.length)errors.objectives='Objectives must be non-blank and unique.';if(value.reference_periods.some(item=>!/^[1-9][0-9]*(m|h|d|w)$/.test(item))||new Set(value.reference_periods).size!==value.reference_periods.length)errors.references='Reference periods must be unique positive offsets.';return errors }
export function validateMetric(value:DraftMetric,other:DraftMetric[]=[]):DraftErrors { const errors:DraftErrors={};if(!/^[a-z][a-z0-9_-]*$/.test(value.id))errors.id='Use a lowercase identifier.';if(!value.name.trim())errors.name='Name is required.';if(value.description!==null&&!value.description.trim())errors.description='Description cannot be blank.';if(!value.metric_id.trim())errors.metric_id='Metric ID is required.';if(!value.source_id)errors.source_id='Select a configured source.';if(!value.query.trim())errors.query='Query is required.';if(!value.unit.trim())errors.unit='Unit is required.';if(value.analysis_objectives.some(item=>!['spike','drift','oscillation'].includes(item))||new Set(value.analysis_objectives).size!==value.analysis_objectives.length)errors.objectives='Use each supported objective at most once.';if(value.reference_periods.some(item=>!/^[1-9][0-9]*(m|h|d|w)$/.test(item))||new Set(value.reference_periods).size!==value.reference_periods.length)errors.references='Reference periods must be unique positive offsets.';if(other.some(item=>item.clientKey!==value.clientKey&&item.id===value.id))errors.id='Metric Lens ID must be unique.';return errors }
const descriptorValid=(value:SemanticDescriptor)=>Boolean(value.trend&&(value.trend.direction||value.trend.rate)||value.variability)
const descriptorMapValid=(values:Record<string,SemanticDescriptor>)=>Object.entries(values).every(([lens,descriptor])=>lens&&descriptorValid(descriptor)&&(!descriptor.trend||(!descriptor.trend.direction||['increasing','decreasing','stable'].includes(descriptor.trend.direction))&&(!descriptor.trend.rate||['slow','moderate','fast'].includes(descriptor.trend.rate)))&&(!descriptor.variability||['low','moderate','high'].includes(descriptor.variability.state)))
/** Validates the constrained, Metric-only Relationship topology and vocabulary. */
export function validateRelationship(value:DraftRelationship,metrics:DraftMetric[],other:DraftRelationship[]=[]):DraftErrors { const errors:DraftErrors={};const referenced=new Set([...Object.keys(value.conditions),...Object.keys(value.expected)]),participants=new Set(value.participants),known=new Set(metrics.map(item=>item.id));if(!/^[a-z][a-z0-9_-]*$/.test(value.id))errors.id='Use a lowercase identifier.';if(!value.name.trim())errors.name='Name is required.';if(value.description!==null&&!value.description.trim())errors.description='Description cannot be blank.';if(other.some(item=>item.clientKey!==value.clientKey&&item.id===value.id))errors.id='Relationship ID must be unique.';if(value.participants.length<2||participants.size!==value.participants.length)errors.participants='Select 2 or more distinct Metric Lens participants.';else if(value.participants.some(item=>!known.has(item)))errors.participants='Relationship participants must be current Metric Lenses.';if(!Object.keys(value.expected).length)errors.expected='Add at least one expected descriptor.';if(!descriptorMapValid(value.conditions)||!descriptorMapValid(value.expected))errors.descriptors='Use only the supported current-state descriptor values.';if([...referenced].some(item=>!participants.has(item))||[...participants].some(item=>!referenced.has(item)))errors.topology='Every participant must appear in a condition or expectation.';return errors }
export function validateDraft(draft:ObservationDraft):DraftErrors { const errors:DraftErrors={};if(!draft.name.trim())errors.name='Name is required.';if(!draft.objective.trim())errors.objective='Objective is required.';if(draft.lenses.length+draft.alert_lenses.length===0)errors.aggregate='Configure at least one Lens.';draft.lenses.forEach((item,index)=>Object.entries(validateMetric(item,draft.lenses)).forEach(([field,message])=>errors[`lenses.${index}.${field}`]=message));draft.alert_lenses.forEach((item,index)=>Object.entries(validateAlert(item,draft.alert_lenses)).forEach(([field,message])=>errors[`alert_lenses.${index}.${field}`]=message));draft.relationships.forEach((item,index)=>Object.entries(validateRelationship(item,draft.lenses,draft.relationships)).forEach(([field,message])=>errors[`relationships.${index}.${field}`]=message));return errors }
export function serializeDraft(draft:ObservationDraft):ObservationCreate { return {name:draft.name,description:draft.description===''?null:draft.description,objective:draft.objective,lenses:draft.lenses.map(metric=>({id:metric.id,name:metric.name,description:metric.description,type:metric.type,metric_id:metric.metric_id,adapter_type:metric.adapter_type,source_id:metric.source_id,query:metric.query,unit:metric.unit,analysis_objectives:metric.analysis_objectives,reference_periods:metric.reference_periods})),alert_lenses:draft.alert_lenses.map(alert=>({id:alert.id,name:alert.name,description:alert.description,type:alert.type,source:alert.source,selector:alert.selector,analysis_objectives:alert.analysis_objectives,reference_periods:alert.reference_periods})),relationships:draft.relationships.map(relationship=>({id:relationship.id,name:relationship.name,description:relationship.description,participants:relationship.participants,conditions:relationship.conditions,expected:relationship.expected}))} }
type CapabilityState={status:'idle'|'pending'|'success'|'empty'|'failure';capabilities?:DefinitionCapabilities;error?:string}
interface DraftContextValue { draft:ObservationDraft|null; explicitErrors:DraftErrors; fresh:()=>void; clear:()=>void; setExplicitErrors:(errors:DraftErrors)=>void; updateGeneral:(value:Pick<ObservationDraft,'name'|'description'|'objective'>)=>void; upsertAlert:(value:DraftAlert,key:string)=>void; upsertMetric:(value:DraftMetric,key:string)=>void; upsertRelationship:(value:DraftRelationship,key:string)=>void; capabilities:CapabilityState; loadCapabilities:()=>void; cancelCapabilities:()=>void }
const DraftContext=createContext<DraftContextValue|null>(null)
/** Owns the in-memory aggregate only while the create route branch is mounted. */
export function ObservationDraftProvider({children}:{children:ReactNode}) { const [draft,dispatch]=useReducer(reducer,null),[explicitErrors,setExplicitErrors]=useState<DraftErrors>({}),[capabilities,setCapabilities]=useState<CapabilityState>({status:'idle'}),request=useRef<{id:number;controller:AbortController}|null>(null),sequence=useRef(0);const cancelCapabilities=useCallback(()=>{const active=request.current;if(!active)return;request.current=null;sequence.current+=1;active.controller.abort();setCapabilities({status:'idle'})},[]);useEffect(()=>cancelCapabilities,[cancelCapabilities]);const loadCapabilities=useCallback(()=>{const previous=request.current;if(previous){request.current=null;previous.controller.abort()}const id=++sequence.current,controller=new AbortController();request.current={id,controller};setCapabilities({status:'pending'});getDefinitionCapabilities(controller.signal).then(result=>{if(request.current?.id!==id||controller.signal.aborted)return;request.current=null;const sources=result.metric.flatMap(adapter=>adapter.sources);setCapabilities(sources.length?{status:'success',capabilities:result}:{status:'empty',capabilities:result})}).catch(error=>{if(request.current?.id!==id||controller.signal.aborted)return;request.current=null;setCapabilities({status:'failure',error:error instanceof Error?error.message:'Unable to load Metric sources.'})})},[]);const fresh=useCallback(()=>{setExplicitErrors({});dispatch({type:'fresh'})},[]),clear=useCallback(()=>{setExplicitErrors({});dispatch({type:'clear'})},[]);const value=useMemo(()=>({draft,explicitErrors,fresh,clear,setExplicitErrors,updateGeneral:(value:Pick<ObservationDraft,'name'|'description'|'objective'>)=>dispatch({type:'general',value}),upsertAlert:(value:DraftAlert,key:string)=>dispatch({type:'upsert-alert',value,key:key==='new'?'new':key}),upsertMetric:(value:DraftMetric,key:string)=>dispatch({type:'upsert-metric',value,key:key==='new'?'new':key}),upsertRelationship:(value:DraftRelationship,key:string)=>dispatch({type:'upsert-relationship',value,key:key==='new'?'new':key}),capabilities,loadCapabilities,cancelCapabilities}),[draft,explicitErrors,fresh,clear,capabilities,loadCapabilities,cancelCapabilities]);return <DraftContext.Provider value={value}>{children}</DraftContext.Provider> }
/** Reads the nearest create-route draft provider. */
export function useObservationDraft(){const value=useContext(DraftContext);if(!value)throw new Error('ObservationDraftProvider is required');return value}
export const newAlert=(key:string):DraftAlert=>({clientKey:key,id:'',name:'',description:null,type:'alert',source:'jira_track_and_release',selector:{query:''},analysis_objectives:[],reference_periods:[]})
export const newMetric=(key:string):DraftMetric=>({clientKey:key,id:'',name:'',description:null,type:'metric',metric_id:'',adapter_type:'prometheus',source_id:'',query:'',unit:'',analysis_objectives:[],reference_periods:[]})
export const newRelationship=(key:string):DraftRelationship=>({clientKey:key,id:'',name:'',description:null,participants:[],conditions:{},expected:{}})
