/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useMemo, useReducer, type ReactNode } from 'react'
import type { AlertLensCreate, ObservationCreate } from './types'
export interface DraftAlert extends AlertLensCreate { clientKey:string }
export interface ObservationDraft { name:string; description:string; objective:string; lenses:never[]; alert_lenses:DraftAlert[]; relationships:never[] }
export type DraftErrors=Record<string,string>
const blank=():ObservationDraft=>({name:'',description:'',objective:'',lenses:[],alert_lenses:[],relationships:[]})
type Action={type:'fresh'}|{type:'general';value:Pick<ObservationDraft,'name'|'description'|'objective'>}|{type:'upsert-alert';value:DraftAlert;key:'new'|string}|{type:'clear'}
function reducer(state:ObservationDraft|null,action:Action):ObservationDraft|null { if(action.type==='fresh')return blank();if(action.type==='clear')return null;if(!state)return state;if(action.type==='general')return {...state,...action.value};if(action.key==='new')return {...state,alert_lenses:[...state.alert_lenses,action.value]};const index=state.alert_lenses.findIndex(item=>item.clientKey===action.key);return index<0?state:{...state,alert_lenses:state.alert_lenses.map((item,i)=>i===index?action.value:item)} }
export function validateAlert(value:DraftAlert,other:DraftAlert[]=[]):DraftErrors { const errors:DraftErrors={};if(!/^[a-z][a-z0-9_-]*$/.test(value.id))errors.id='Use a lowercase identifier.';if(!value.name.trim())errors.name='Name is required.';if(value.description!==null&&!value.description.trim())errors.description='Description cannot be blank.';if(!value.selector.query.trim())errors.query='Selector query is required.';if(other.some(item=>item.clientKey!==value.clientKey&&item.id===value.id))errors.id='Alert Lens ID must be unique.';if(value.analysis_objectives.some(item=>!item.trim())||new Set(value.analysis_objectives).size!==value.analysis_objectives.length)errors.objectives='Objectives must be non-blank and unique.';if(value.reference_periods.some(item=>!/^[1-9][0-9]*(m|h|d|w)$/.test(item))||new Set(value.reference_periods).size!==value.reference_periods.length)errors.references='Reference periods must be unique positive offsets.';return errors }
export function validateDraft(draft:ObservationDraft):DraftErrors { const errors:DraftErrors={};if(!draft.name.trim())errors.name='Name is required.';if(!draft.objective.trim())errors.objective='Objective is required.';if(draft.alert_lenses.length===0)errors.aggregate='Configure at least one Lens.';draft.alert_lenses.forEach((item,index)=>Object.entries(validateAlert(item,draft.alert_lenses)).forEach(([field,message])=>errors[`alert_lenses.${index}.${field}`]=message));return errors }
export function serializeDraft(draft:ObservationDraft):ObservationCreate { return {name:draft.name,description:draft.description===''?null:draft.description,objective:draft.objective,lenses:[],alert_lenses:draft.alert_lenses.map(alert=>({id:alert.id,name:alert.name,description:alert.description,type:alert.type,source:alert.source,selector:alert.selector,analysis_objectives:alert.analysis_objectives,reference_periods:alert.reference_periods})),relationships:[]} }
interface DraftContextValue { draft:ObservationDraft|null; fresh:()=>void; clear:()=>void; updateGeneral:(value:Pick<ObservationDraft,'name'|'description'|'objective'>)=>void; upsertAlert:(value:DraftAlert,key:string)=>void }
const DraftContext=createContext<DraftContextValue|null>(null)
/** Owns the in-memory aggregate only while the create route branch is mounted. */
export function ObservationDraftProvider({children}:{children:ReactNode}) { const [draft,dispatch]=useReducer(reducer,null);const value=useMemo(()=>({draft,fresh:()=>dispatch({type:'fresh'}),clear:()=>dispatch({type:'clear'}),updateGeneral:(value:Pick<ObservationDraft,'name'|'description'|'objective'>)=>dispatch({type:'general',value}),upsertAlert:(value:DraftAlert,key:string)=>dispatch({type:'upsert-alert',value,key:key==='new'?'new':key})}),[draft]);return <DraftContext.Provider value={value}>{children}</DraftContext.Provider> }
/** Reads the nearest create-route draft provider. */
export function useObservationDraft(){const value=useContext(DraftContext);if(!value)throw new Error('ObservationDraftProvider is required');return value}
export const newAlert=(key:string):DraftAlert=>({clientKey:key,id:'',name:'',description:null,type:'alert',source:'jira_track_and_release',selector:{query:''},analysis_objectives:[],reference_periods:[]})
