import { describe, expect, it } from 'vitest'
import { generateObservationChildId, hydrateDraft, newAlert, newMetric, serializeDraft, validateAlert, validateDraft, validateMetric, type ObservationDraft } from './draft'
import type { ObservationResponse } from './types'

describe('Observation child ID generation',()=>{
  const randomUuid='A1B2C3D4-e5f6-4a1b-8c9d-001122334455',randomPart='a1b2c3d4'
  it('generates typed IDs for every child kind from injected UUID randomness',()=>{expect(generateObservationChildId('Cooling Pressure','metric',[],randomUuid)).toBe(`metr_cooling_pressure_${randomPart}`);expect(generateObservationChildId('Release alerts','alert',[],randomUuid)).toBe(`alrt_release_alerts_${randomPart}`);expect(generateObservationChildId('Pressure and flow','relationship',[],randomUuid)).toBe(`rel_pressure_and_flow_${randomPart}`)})
  it('normalizes decomposable Latin diacritics and falls back to item without a leading ASCII letter',()=>{expect(generateObservationChildId('Crème Pressure','relationship',[],randomUuid)).toBe(`rel_creme_pressure_${randomPart}`);expect(generateObservationChildId('Тиск','alert',[],randomUuid)).toBe(`alrt_item_${randomPart}`);expect(generateObservationChildId('123 pressure','relationship',[],randomUuid)).toBe(`rel_item_${randomPart}`)})
  it('preserves fixed typed components and the 255-character boundary through collisions',()=>{const name='a'.repeat(300),first=generateObservationChildId(name,'metric',[],randomUuid),second=generateObservationChildId(name,'metric',[first],randomUuid),third=generateObservationChildId(name,'metric',[first,second],randomUuid);expect(first).toHaveLength(255);expect(first.endsWith(`_${randomPart}`)).toBe(true);expect(second).toHaveLength(255);expect(second.endsWith(`_${randomPart}_2`)).toBe(true);expect(third).toHaveLength(255);expect(third.endsWith(`_${randomPart}_3`)).toBe(true);expect(new Set([first,second,third])).toHaveLength(3)})
  it('treats only supplied sibling IDs as collisions and keeps identical inputs stable',()=>{const candidate=generateObservationChildId('Shared','metric',[],randomUuid);expect(generateObservationChildId('Shared','metric',[],randomUuid)).toBe(candidate);expect(generateObservationChildId('Shared','alert',[],randomUuid)).not.toBe(candidate);expect(generateObservationChildId('Shared','metric',[candidate],randomUuid)).toBe(`${candidate}_2`)})
})

const alert={...newAlert('client-a'),id:'release_alerts',name:'Release alerts',selector:{query:' project = REL  AND status != Done '},analysis_objectives:['Assess recurrence','Compare recurrence'],reference_periods:['1d','7d']}
describe('Observation Alert draft contracts',()=>{
  it('serializes Alert-only data in order without the UI-only key or rewriting an opaque query',()=>{const draft:ObservationDraft={name:'Release health',description:'',objective:'Observe releases',operational_context:'',lenses:[],alert_lenses:[alert],relationships:[]};expect(serializeDraft(draft)).toEqual({name:'Release health',description:null,objective:'Observe releases',operational_context:null,lenses:[],alert_lenses:[{id:'release_alerts',name:'Release alerts',description:null,type:'alert',source:'jira_track_and_release',selector:{query:' project = REL  AND status != Done '},analysis_objectives:['Assess recurrence','Compare recurrence'],reference_periods:['1d','7d']}],relationships:[]})})
  it('enforces Alert and aggregate invariants without mutating draft values',()=>{expect(validateAlert({...alert,id:'BAD',analysis_objectives:['same','same'],reference_periods:['0m','1d','1d']})).toMatchObject({id:'Use a lowercase identifier.',objectives:'Objectives must be non-blank and unique.',references:'Reference periods must be unique positive offsets.'});expect(validateDraft({name:'',description:'',objective:'',lenses:[],alert_lenses:[],relationships:[]})).toMatchObject({name:'Name is required.',objective:'Objective is required.',aggregate:'Configure at least one Lens.'})})
})
const metric={...newMetric('metric-key'),id:'cpu',name:'CPU utilization',metric_id:'node_cpu',adapter_type:'prometheus' as const,source_id:'primary',query:'rate(cpu[5m])',unit:'%',analysis_objectives:['spike','drift'] as ('spike'|'drift')[],reference_periods:['1d','7d']}
describe('Observation Metric draft contracts',()=>{
  it('serializes Metric-only and mixed cross-type identity in exact collection order without UI fields',()=>{const draft:ObservationDraft={name:'Mixed',description:'Description',objective:'Observe',operational_context:'',lenses:[metric],alert_lenses:[{...alert,id:'cpu'}],relationships:[]};expect(serializeDraft(draft)).toEqual({name:'Mixed',description:'Description',objective:'Observe',operational_context:null,lenses:[{id:'cpu',name:'CPU utilization',description:null,type:'metric',metric_id:'node_cpu',adapter_type:'prometheus',source_id:'primary',query:'rate(cpu[5m])',unit:'%',analysis_objectives:['spike','drift'],reference_periods:['1d','7d']}],alert_lenses:[{id:'cpu',name:'Release alerts',description:null,type:'alert',source:'jira_track_and_release',selector:{query:' project = REL  AND status != Done '},analysis_objectives:['Assess recurrence','Compare recurrence'],reference_periods:['1d','7d']}],relationships:[]})})
  it('enforces Metric contract values and only type-local duplicate identity',()=>{expect(validateMetric({...metric,id:'BAD',analysis_objectives:['spike','spike'] as never,reference_periods:['0m','1d','1d']})).toMatchObject({id:'Use a lowercase identifier.',objectives:'Use each supported objective at most once.',references:'Reference periods must be unique positive offsets.'});expect(validateDraft({name:'Metric',description:'',objective:'Observe',lenses:[metric],alert_lenses:[{...alert,id:'cpu'}],relationships:[]})).toEqual({})})
})

describe('Persisted aggregate draft hydration',()=>{
  it('keeps canonical child order and IDs while excluding response-only links and version fields',()=>{
    const response={id:'observation-1',schema_version:1,href:'/api/v1/observations/observation-1',name:'Mixed',description:null,objective:'Observe',lenses:[{...metric,href:'/metric',observation_href:'/observation'}],alert_lenses:[{...alert,href:'/alert',observation_href:'/observation'}],relationships:[]} as unknown as ObservationResponse
    expect(hydrateDraft(response)).toMatchObject({name:'Mixed',description:'',objective:'Observe',lenses:[{id:'cpu',name:'CPU utilization'}],alert_lenses:[{id:'release_alerts',name:'Release alerts'}]})
    expect(serializeDraft(hydrateDraft(response))).toEqual({name:'Mixed',description:null,objective:'Observe',operational_context:null,lenses:[{id:'cpu',name:'CPU utilization',description:null,type:'metric',metric_id:'node_cpu',adapter_type:'prometheus',source_id:'primary',query:'rate(cpu[5m])',unit:'%',analysis_objectives:['spike','drift'],reference_periods:['1d','7d']}],alert_lenses:[{id:'release_alerts',name:'Release alerts',description:null,type:'alert',source:'jira_track_and_release',selector:{query:' project = REL  AND status != Done '},analysis_objectives:['Assess recurrence','Compare recurrence'],reference_periods:['1d','7d']}],relationships:[]})
  })
})

describe('Operational context draft contract',()=>{
  const complete=():ObservationDraft=>({name:'Cooling',description:'',objective:'Observe',operational_context:'  startup\nterminology  ',lenses:[metric],alert_lenses:[],relationships:[]})
  it('hydrates and serializes exact text, validates Unicode code points, and turns only empty text into null',()=>{
    expect(serializeDraft(complete()).operational_context).toBe('  startup\nterminology  ')
    expect(serializeDraft({...complete(),operational_context:''}).operational_context).toBeNull()
    expect(validateDraft({...complete(),operational_context:' \n '})).toMatchObject({operational_context:'Operational context cannot be blank.'})
    expect(validateDraft({...complete(),operational_context:'😀'.repeat(4001)})).toMatchObject({operational_context:'Operational context must be at most 4,000 Unicode code points.'})
    expect(hydrateDraft({id:'o',name:'Cooling',description:null,objective:'Observe',operational_context:'line one\nline two',schema_version:1,lenses:[],alert_lenses:[],relationships:[],href:'/o'})).toMatchObject({operational_context:'line one\nline two'})
  })
})
