import { describe, expect, it } from 'vitest'
import { generateObservationChildId, newAlert, newMetric, serializeDraft, validateAlert, validateDraft, validateMetric, type ObservationDraft } from './draft'

describe('Observation child ID generation',()=>{
  const generatedAt=1_700_000_000_000,suffix=generatedAt.toString(36)
  it('normalizes readable names and decomposable Latin diacritics deterministically',()=>{expect(generateObservationChildId('  Cooling Pressure  ','metric',[],generatedAt)).toBe(`cooling_pressure_${suffix}`);expect(generateObservationChildId('Crème Pressure','relationship',[],generatedAt)).toBe(`creme_pressure_${suffix}`)})
  it('uses type fallbacks when normalization has no leading ASCII letter',()=>{expect(generateObservationChildId('Тиск','alert',[],generatedAt)).toBe(`alert_${suffix}`);expect(generateObservationChildId('123 pressure','relationship',[],generatedAt)).toBe(`relationship_${suffix}`)})
  it('preserves suffixes and the 255-character boundary through collisions',()=>{const name='a'.repeat(300),first=generateObservationChildId(name,'metric',[],generatedAt),second=generateObservationChildId(name,'metric',[first],generatedAt),third=generateObservationChildId(name,'metric',[first,second],generatedAt);expect(first).toHaveLength(255);expect(first.endsWith(`_${suffix}`)).toBe(true);expect(second).toHaveLength(255);expect(second.endsWith(`_${suffix}_2`)).toBe(true);expect(third).toHaveLength(255);expect(third.endsWith(`_${suffix}_3`)).toBe(true);expect(new Set([first,second,third])).toHaveLength(3)})
  it('treats only supplied sibling IDs as collisions',()=>{const candidate=generateObservationChildId('Shared','alert',[],generatedAt);expect(generateObservationChildId('Shared','metric',[],generatedAt)).toBe(candidate);expect(generateObservationChildId('Shared','metric',[candidate],generatedAt)).toBe(`${candidate}_2`)})
})

const alert={...newAlert('client-a'),id:'release_alerts',name:'Release alerts',selector:{query:' project = REL  AND status != Done '},analysis_objectives:['Assess recurrence','Compare recurrence'],reference_periods:['1d','7d']}
describe('Observation Alert draft contracts',()=>{
  it('serializes Alert-only data in order without the UI-only key or rewriting an opaque query',()=>{const draft:ObservationDraft={name:'Release health',description:'',objective:'Observe releases',lenses:[],alert_lenses:[alert],relationships:[]};expect(serializeDraft(draft)).toEqual({name:'Release health',description:null,objective:'Observe releases',lenses:[],alert_lenses:[{id:'release_alerts',name:'Release alerts',description:null,type:'alert',source:'jira_track_and_release',selector:{query:' project = REL  AND status != Done '},analysis_objectives:['Assess recurrence','Compare recurrence'],reference_periods:['1d','7d']}],relationships:[]})})
  it('enforces Alert and aggregate invariants without mutating draft values',()=>{expect(validateAlert({...alert,id:'BAD',analysis_objectives:['same','same'],reference_periods:['0m','1d','1d']})).toMatchObject({id:'Use a lowercase identifier.',objectives:'Objectives must be non-blank and unique.',references:'Reference periods must be unique positive offsets.'});expect(validateDraft({name:'',description:'',objective:'',lenses:[],alert_lenses:[],relationships:[]})).toMatchObject({name:'Name is required.',objective:'Objective is required.',aggregate:'Configure at least one Lens.'})})
})
const metric={...newMetric('metric-key'),id:'cpu',name:'CPU utilization',metric_id:'node_cpu',adapter_type:'prometheus' as const,source_id:'primary',query:'rate(cpu[5m])',unit:'%',analysis_objectives:['spike','drift'] as ('spike'|'drift')[],reference_periods:['1d','7d']}
describe('Observation Metric draft contracts',()=>{
  it('serializes Metric-only and mixed cross-type identity in exact collection order without UI fields',()=>{const draft:ObservationDraft={name:'Mixed',description:'Description',objective:'Observe',lenses:[metric],alert_lenses:[{...alert,id:'cpu'}],relationships:[]};expect(serializeDraft(draft)).toEqual({name:'Mixed',description:'Description',objective:'Observe',lenses:[{id:'cpu',name:'CPU utilization',description:null,type:'metric',metric_id:'node_cpu',adapter_type:'prometheus',source_id:'primary',query:'rate(cpu[5m])',unit:'%',analysis_objectives:['spike','drift'],reference_periods:['1d','7d']}],alert_lenses:[{id:'cpu',name:'Release alerts',description:null,type:'alert',source:'jira_track_and_release',selector:{query:' project = REL  AND status != Done '},analysis_objectives:['Assess recurrence','Compare recurrence'],reference_periods:['1d','7d']}],relationships:[]})})
  it('enforces Metric contract values and only type-local duplicate identity',()=>{expect(validateMetric({...metric,id:'BAD',analysis_objectives:['spike','spike'] as never,reference_periods:['0m','1d','1d']})).toMatchObject({id:'Use a lowercase identifier.',objectives:'Use each supported objective at most once.',references:'Reference periods must be unique positive offsets.'});expect(validateDraft({name:'Metric',description:'',objective:'Observe',lenses:[metric],alert_lenses:[{...alert,id:'cpu'}],relationships:[]})).toEqual({})})
})
