import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import App from '../../App'

const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status})
const capabilities={metric:[{adapter_type:'prometheus',sources:[{id:'primary',name:'Primary Prometheus'},{id:'secondary',name:'Secondary Prometheus'}]}]}
const renderAt=(path='/observations/new')=>render(<MemoryRouter initialEntries={[path]}><App/></MemoryRouter>)
async function openMetric(user:ReturnType<typeof userEvent.setup>){await user.click(await screen.findByText('Add Metric Lens'));return screen.findByRole('heading',{name:'Metric Lens Configuration'})}
async function fillMetric(user:ReturnType<typeof userEvent.setup>,id='cpu'){await user.type(screen.getByLabelText('Lens ID'),id);await user.type(screen.getByLabelText('Name'),'CPU utilization');await user.type(screen.getByLabelText('Metric ID'),'node_cpu');await user.type(screen.getByLabelText('Unit'),'%');await user.selectOptions(screen.getByLabelText('Metric source'),'primary');await user.type(screen.getByLabelText('Provider query'),'rate(cpu[5m])');await user.click(screen.getByLabelText('spike'));await user.click(screen.getByText('Add reference period'));await user.type(screen.getByLabelText('Reference period 1'),'1d')}
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals()})
describe('Metric Lens editor',()=>{
  it('shows pending, failure/retry, and empty states while Apply is unavailable',async()=>{const user=userEvent.setup(),fetchMock=vi.fn().mockResolvedValueOnce(response({code:'down',message:'Capability down'},503)).mockResolvedValueOnce(response({metric:[]}));vi.stubGlobal('fetch',fetchMock);renderAt();await openMetric(user);expect((screen.getByRole('button',{name:'Apply changes'}) as HTMLButtonElement).disabled).toBe(true);expect(await screen.findByText(/Unable to load Metric sources/)).toBeTruthy();await user.click(screen.getByText('Retry'));expect(await screen.findByText(/No Metric source is configured/)).toBeTruthy();expect((screen.getByRole('button',{name:'Apply changes'}) as HTMLButtonElement).disabled).toBe(true);expect(fetchMock.mock.calls.map(([url])=>url)).toEqual(['/api/v1/observation-definition-capabilities','/api/v1/observation-definition-capabilities'])})
  it('applies a supported Metric once locally, preserves same-position opaque-key replacement, and makes no write',async()=>{const user=userEvent.setup(),fetchMock=vi.fn().mockResolvedValue(response(capabilities));vi.stubGlobal('fetch',fetchMock);renderAt();await openMetric(user);await screen.findByRole('option',{name:'Primary Prometheus'});await fillMetric(user);await user.click(screen.getByText('Apply changes'));expect(screen.getByText('CPU utilization')).toBeTruthy();expect(fetchMock.mock.calls).toHaveLength(1);await user.click(screen.getByText('Edit'));await user.clear(screen.getByLabelText('Name'));await user.type(screen.getByLabelText('Name'),'Updated CPU');await user.click(screen.getByText('Apply changes'));expect(screen.getByText('Updated CPU')).toBeTruthy();expect(fetchMock.mock.calls).toHaveLength(1)})
  it('cancels local Metric edits and explains excluded free text/history without a write',async()=>{const user=userEvent.setup(),fetchMock=vi.fn().mockResolvedValue(response(capabilities));vi.stubGlobal('fetch',fetchMock);renderAt();await openMetric(user);await screen.findByRole('option',{name:'Primary Prometheus'});expect(screen.getByText(/Free-text Metric objectives require a backend contract change/)).toBeTruthy();expect(screen.getByText(/no history field/)).toBeTruthy();await user.type(screen.getByLabelText('Lens ID'),'discarded');await user.click(screen.getByText('Cancel'));expect(screen.queryByText('discarded')).toBeNull();expect(fetchMock.mock.calls).toHaveLength(1)})
})
