import { cleanup, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { BrowserRouter, MemoryRouter } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import App from '../../App'

const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status})
const capabilities={metric:[{adapter_type:'prometheus',sources:[{id:'primary',name:'Primary Prometheus'},{id:'secondary',name:'Secondary Prometheus'}]}]}
const renderAt=(path='/observations/new')=>render(<MemoryRouter initialEntries={[path]}><App/></MemoryRouter>)
async function openMetric(user:ReturnType<typeof userEvent.setup>){await user.click(await screen.findByText('Add Metric Lens'));return screen.findByRole('heading',{name:'Metric Lens Configuration'})}
async function fillMetric(user:ReturnType<typeof userEvent.setup>){await user.type(screen.getByLabelText('Name'),'CPU utilization');await user.type(screen.getByLabelText('Metric ID'),'node_cpu');await user.type(screen.getByLabelText('Unit'),'%');await user.selectOptions(screen.getByLabelText('Metric source'),'primary');await user.type(screen.getByLabelText('Provider query'),'rate(cpu[5m])');await user.click(screen.getByLabelText('spike'));await user.click(screen.getByText('Add reference period'));await user.type(screen.getByLabelText('Reference period 1'),'1d')}
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals()})
describe('Metric Lens editor',()=>{
  it('aborts and invalidates an abandoned pending capability read, ignores its late completion, and reloads on reopen',async()=>{const user=userEvent.setup();let resolveFirst:(value:Response)=>void=()=>{},signal:AbortSignal|undefined;const first=new Promise<Response>(resolve=>{resolveFirst=resolve}),fetchMock=vi.fn().mockImplementationOnce((_url:string,init:RequestInit)=>{signal=init.signal as AbortSignal;return first}).mockResolvedValueOnce(response(capabilities));vi.stubGlobal('fetch',fetchMock);renderAt();await openMetric(user);expect(await screen.findByText(/Loading configured Metric sources/)).toBeTruthy();await user.click(screen.getByText('Cancel'));expect(signal?.aborted).toBe(true);resolveFirst(response({metric:[]}));await user.click(screen.getByText('Add Metric Lens'));expect(await screen.findByRole('option',{name:'Primary Prometheus'})).toBeTruthy();expect(screen.queryByText(/No Metric source is configured/)).toBeNull();expect(fetchMock.mock.calls.map(([url])=>url)).toEqual(['/api/v1/observation-definition-capabilities','/api/v1/observation-definition-capabilities'])})
  it('shows pending, failure/retry, and empty states while Apply is unavailable',async()=>{const user=userEvent.setup(),fetchMock=vi.fn().mockResolvedValueOnce(response({code:'down',message:'Capability down'},503)).mockResolvedValueOnce(response({metric:[]}));vi.stubGlobal('fetch',fetchMock);renderAt();await openMetric(user);expect((screen.getByRole('button',{name:'Apply changes'}) as HTMLButtonElement).disabled).toBe(true);expect(await screen.findByText(/Unable to load Metric sources/)).toBeTruthy();await user.click(screen.getByText('Retry'));expect(await screen.findByText(/No Metric source is configured/)).toBeTruthy();expect((screen.getByRole('button',{name:'Apply changes'}) as HTMLButtonElement).disabled).toBe(true);expect(fetchMock.mock.calls.map(([url])=>url)).toEqual(['/api/v1/observation-definition-capabilities','/api/v1/observation-definition-capabilities'])})
  it('offers every configured source by name without selecting a fallback source',async()=>{const user=userEvent.setup(),fetchMock=vi.fn().mockResolvedValue(response(capabilities));vi.stubGlobal('fetch',fetchMock);renderAt();await openMetric(user);const source=await screen.findByLabelText('Metric source') as HTMLSelectElement
    expect(Array.from(source.options).map(option=>({value:option.value,text:option.text}))).toEqual([{value:'',text:'Select configured source'},{value:'primary',text:'Primary Prometheus'},{value:'secondary',text:'Secondary Prometheus'}])
    expect(source.value).toBe('')
    await user.selectOptions(source,'secondary')
    expect(source.value).toBe('secondary')
    expect(fetchMock).toHaveBeenCalledTimes(1)
  })
  it('applies a supported Metric once locally, preserves its generated ID and opaque key on edit, and makes no write',async()=>{const user=userEvent.setup(),fetchMock=vi.fn().mockResolvedValue(response(capabilities));vi.stubGlobal('fetch',fetchMock);renderAt();await openMetric(user);await screen.findByRole('option',{name:'Primary Prometheus'});await fillMetric(user);const generatedId=screen.getByText(/^\(id: .+\)$/).textContent!.slice(5,-1);expect(generatedId).toMatch(/^metr_cpu_utilization_[a-f0-9]{8}$/);expect(screen.getByLabelText('Name').getAttribute('aria-describedby')).toContain('metric-identity');expect(screen.queryByLabelText('Lens ID')).toBeNull();await user.click(screen.getByText('Apply changes'));expect(screen.getAllByText('CPU utilization').length).toBeGreaterThan(0);expect(fetchMock.mock.calls).toHaveLength(1);await user.click(screen.getByText('Edit'));expect(screen.getByText(`(id: ${generatedId})`)).toBeTruthy();await user.clear(screen.getByLabelText('Name'));await user.type(screen.getByLabelText('Name'),'Updated CPU');await user.click(screen.getByText('Apply changes'));expect(screen.getAllByText('Updated CPU').length).toBeGreaterThan(0);expect(fetchMock.mock.calls).toHaveLength(1)})
  it('cancels local Metric edits and explains excluded free text/history without a write',async()=>{const user=userEvent.setup(),fetchMock=vi.fn().mockResolvedValue(response(capabilities));vi.stubGlobal('fetch',fetchMock);renderAt();await openMetric(user);await screen.findByRole('option',{name:'Primary Prometheus'});expect(screen.getByText(/Free-text Metric objectives require a backend contract change/)).toBeTruthy();expect(screen.getByText(/no history field/)).toBeTruthy();await user.type(screen.getByLabelText('Name'),'Discarded');await user.tab();expect(screen.getByText(/^\(id: metr_discarded_[a-f0-9]{8}\)$/)).toBeTruthy();await user.click(screen.getByText('Cancel'));expect(screen.queryByText('Discarded')).toBeNull();expect(fetchMock.mock.calls).toHaveLength(1)})
  it('aborts pending capability reads on sidebar navigation, browser back, and provider unmount; late failure cannot surface',async()=>{const user=userEvent.setup();const signals:AbortSignal[]=[];let rejectLate:(reason?:unknown)=>void=()=>{},calls=0;const lateFailure=new Promise<Response>((_resolve,reject)=>{rejectLate=reject});const pending=()=>new Promise<Response>(()=>{});const fetchMock=vi.fn().mockImplementation((_url:string,init:RequestInit)=>{signals.push(init.signal as AbortSignal);return calls++===0?lateFailure:pending()});vi.stubGlobal('fetch',fetchMock)
    const first=renderAt();await openMetric(user);await user.click(screen.getByRole('link',{name:'Observations'}));expect(signals[0]?.aborted).toBe(true);rejectLate(new Error('late capability failure'));await Promise.resolve();expect(screen.queryByText(/Unable to load Metric sources/)).toBeNull();first.unmount()
    window.history.replaceState({},'', '/observations/new');const browser=render(<BrowserRouter><App/></BrowserRouter>);await openMetric(user);window.history.back();expect(await screen.findByRole('heading',{name:'Create Observation'})).toBeTruthy();expect(signals[1]?.aborted).toBe(true);browser.unmount()
    const third=renderAt();await openMetric(user);third.unmount();expect(signals[2]?.aborted).toBe(true);cleanup()
  })
  it('keeps settled success, empty, and failure capability state through editor cancel/reopen and only Retry fetches again',async()=>{const user=userEvent.setup();const fetchMock=vi.fn().mockResolvedValueOnce(response(capabilities)).mockResolvedValueOnce(response({metric:[]})).mockResolvedValueOnce(response({code:'down',message:'Capability down'},503)).mockResolvedValueOnce(response(capabilities));vi.stubGlobal('fetch',fetchMock)
    renderAt();await openMetric(user);await screen.findByRole('option',{name:'Primary Prometheus'});await user.click(screen.getByText('Cancel'));await openMetric(user);expect(await screen.findByRole('option',{name:'Primary Prometheus'})).toBeTruthy();expect(fetchMock).toHaveBeenCalledTimes(1);await user.click(screen.getByText('Cancel'))
    cleanup();renderAt();await openMetric(user);expect(await screen.findByText(/No Metric source is configured/)).toBeTruthy();await user.click(screen.getByText('Cancel'));await openMetric(user);expect(screen.getByText(/No Metric source is configured/)).toBeTruthy();expect(fetchMock).toHaveBeenCalledTimes(2);await user.click(screen.getByText('Cancel'))
    cleanup();renderAt();await openMetric(user);expect(await screen.findByText(/Unable to load Metric sources/)).toBeTruthy();await user.click(screen.getByText('Cancel'));await openMetric(user);expect(screen.getByText(/Unable to load Metric sources/)).toBeTruthy();expect(fetchMock).toHaveBeenCalledTimes(3);await user.click(screen.getByText('Retry'));expect(await screen.findByRole('option',{name:'Primary Prometheus'})).toBeTruthy();expect(fetchMock).toHaveBeenCalledTimes(4)
  })
  it('renders frame-12 labels and semantic boundaries without unsupported controls',async()=>{const user=userEvent.setup(),fetchMock=vi.fn().mockResolvedValue(response(capabilities));vi.stubGlobal('fetch',fetchMock);renderAt();await openMetric(user);await screen.findByRole('option',{name:'Primary Prometheus'})
    expect(screen.getByRole('heading',{name:'Metric Lens Configuration'})).toBeTruthy();expect(screen.getByRole('heading',{name:'Lens identity'})).toBeTruthy();for(const label of ['Name','Metric ID','Unit','Metric source','Provider query'])expect(screen.getByLabelText(label)).toBeTruthy();expect(screen.queryByLabelText('Lens ID')).toBeNull();expect((screen.getByRole('button',{name:'Apply changes'}) as HTMLButtonElement).disabled).toBe(false);expect(screen.getByText(/One Metric Lens observes exactly one metric/)).toBeTruthy();expect(screen.getByText(/Free-text Metric objectives require a backend contract change/)).toBeTruthy();expect(screen.getByText(/Persisted-history policy is not available/)).toBeTruthy();expect(screen.queryByRole('button',{name:/preflight|tool/i})).toBeNull();expect(screen.queryByLabelText(/history|preflight|tool/i)).toBeNull();expect(fetchMock.mock.calls.filter(([,init])=>(init as RequestInit | undefined)?.method==='POST')).toEqual([])
  })
  it('keeps Metric Lens guidance and examples visible while errors remain accessible',async()=>{const user=userEvent.setup(),fetchMock=vi.fn().mockResolvedValue(response(capabilities));vi.stubGlobal('fetch',fetchMock);renderAt();await openMetric(user);await screen.findByRole('option',{name:'Primary Prometheus'})
    for(const instruction of ['Human-readable name shown in this Observation. An ID is generated after the initial non-empty name is entered.','Optional context for this metric perspective.','Provider metric identifier for the one metric this Lens observes.','Unit returned by the provider for this metric.','Configured source used to retrieve this metric.','Provider-native query for the selected metric source.'])expect(screen.getByText(instruction)).toBeTruthy()
    for(const placeholder of ['Cooling pressure','Tracks cooling-loop pressure over time.','process_pressure_bar','bar','rate(process_pressure_total[5m])'])expect(screen.getByPlaceholderText(placeholder)).toBeTruthy()
    await user.click(screen.getByRole('button',{name:'Apply changes'}))
    const name=screen.getByLabelText('Name')
    expect(name.getAttribute('aria-invalid')).toBe('true')
    const descriptions=name.getAttribute('aria-describedby')?.split(' ')??[]
    expect(descriptions).toHaveLength(2)
    expect(descriptions.map(id=>document.getElementById(id)?.textContent)).toEqual(expect.arrayContaining(['Human-readable name shown in this Observation. An ID is generated after the initial non-empty name is entered.','Name is required.']))
    expect(fetchMock.mock.calls).toHaveLength(1)
  })
  it('focuses one retained invalid-Apply summary until the next Apply replaces it without mutating the draft',async()=>{const user=userEvent.setup(),fetchMock=vi.fn().mockResolvedValue(response(capabilities));vi.stubGlobal('fetch',fetchMock);renderAt();await openMetric(user);await screen.findByRole('option',{name:'Primary Prometheus'})
    await user.click(screen.getByRole('button',{name:'Apply changes'}));const first=await screen.findByRole('alert',{name:'Metric Lens changes cannot be applied'});expect(document.activeElement).toBe(first);expect(first.textContent).toContain('Use a lowercase identifier.');const name=screen.getByLabelText('Name');const idCorrection=screen.getByText('Use a lowercase identifier.').parentElement!.querySelector('a')!;expect(idCorrection.getAttribute('href')).toBe('#metric-name');Object.defineProperty(HTMLElement.prototype,'scrollIntoView',{configurable:true,value:vi.fn()});await user.click(idCorrection);expect(document.activeElement).toBe(name);expect(name.getAttribute('aria-invalid')).toBe('true')
    await user.type(name,'CPU');expect(screen.getByRole('alert',{name:'Metric Lens changes cannot be applied'}).textContent).toContain('Use a lowercase identifier.');expect(name.getAttribute('aria-invalid')).toBe('true');expect(screen.queryByRole('heading',{name:'Create Observation'})).toBeNull()
    await user.click(screen.getByRole('button',{name:'Apply changes'}));const replacement=await screen.findByRole('alert',{name:'Metric Lens changes cannot be applied'});expect(document.activeElement).toBe(replacement);expect(replacement.textContent).not.toContain('Use a lowercase identifier.');expect(name.getAttribute('aria-invalid')).toBeNull();expect(screen.getByRole('heading',{name:'Metric Lens Configuration'})).toBeTruthy();expect(fetchMock.mock.calls.filter(([,init])=>(init as RequestInit|undefined)?.method==='POST')).toEqual([])
  })
})
