import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter, Route, Routes, useNavigate } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { ObservationDetailPage } from './ObservationDetailPage'

const detail={id:'a',name:'Database Health',description:'A description',objective:'Observe safely',schema_version:1,lenses:[{id:'m1',name:'First metric',type:'metric',href:'/m1',description:null,metric_id:'first',adapter_type:'prometheus',source_id:'source',query:'up',unit:'%',analysis_objectives:[],reference_periods:['1d'],observation_href:'/a'},{id:'m2',name:'Second metric',type:'metric',href:'/m2',description:null,metric_id:'second',adapter_type:'prometheus',source_id:'source',query:'up',unit:'%',analysis_objectives:[],reference_periods:['7d'],observation_href:'/a'}],alert_lenses:[{id:'a1',name:'First alert',type:'alert',href:'/a1',description:null,source:'jira_track_and_release',selector:{query:'project=X'},analysis_objectives:[],reference_periods:[],observation_href:'/a'}],relationships:[{id:'r1',name:'First relationship',href:'/r1',description:null,participants:['m1','m2'],conditions:{},expected:{},observation_href:'/a'}],href:'/a'}
function deferred<T>() { let resolve:(value:T)=>void;let reject:(reason?:unknown)=>void;const promise=new Promise<T>((res,rej)=>{resolve=res;reject=rej});return {promise,resolve:resolve!,reject:reject!} }
function Navigator(){const navigate=useNavigate();return <button onClick={()=>navigate('/observations/b')}>Next definition</button>}
function renderDetail(extra=false){return render(<MemoryRouter initialEntries={['/observations/a']}><Navigator/>{extra?null:null}<Routes><Route path="/observations/:observationId" element={<ObservationDetailPage/>}/><Route path="/observations" element={<p>Definition list</p>}/></Routes></MemoryRouter>)}
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals()})
describe('ObservationDetailPage',()=>{
  it('keeps creation confirmation visible while the destination is loading or fails',async()=>{const request=deferred<Response>();vi.stubGlobal('fetch',vi.fn().mockReturnValue(request.promise));render(<MemoryRouter initialEntries={[{pathname:'/observations/a',state:{created:true}}]}><Routes><Route path="/observations/:observationId" element={<ObservationDetailPage/>}/></Routes></MemoryRouter>);expect(screen.getByText(/created successfully/i)).toBeTruthy();request.resolve(new Response('{}',{status:500}));expect(await screen.findByText(/Unable to load/i)).toBeTruthy();expect(screen.getByText(/created successfully/i)).toBeTruthy()})
  it('confirms a successful create without adding runtime semantics',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify(detail),{status:200})));render(<MemoryRouter initialEntries={[{pathname:'/observations/a',state:{created:true}}]}><Routes><Route path="/observations/:observationId" element={<ObservationDetailPage/>}/></Routes></MemoryRouter>);expect(await screen.findByText(/created successfully/i)).toBeTruthy();expect(screen.queryByText(/Run Observation/i)).toBeNull()})
  it('shows pending then ordered read-only metadata and child summaries without monitoring controls',async()=>{const request=deferred<Response>();vi.stubGlobal('fetch',vi.fn().mockReturnValue(request.promise));renderDetail();expect(screen.getByText('Loading definition')).toBeTruthy();request.resolve(new Response(JSON.stringify(detail),{status:200}));expect(await screen.findByText('Observe safely')).toBeTruthy();const metrics=screen.getAllByText(/metric/i).map(node=>node.textContent);expect(metrics.indexOf('First metric')).toBeLessThan(metrics.indexOf('Second metric'));expect(screen.getByText('First alert')).toBeTruthy();expect(screen.getByText('First relationship')).toBeTruthy();expect(screen.queryByText(/Run Observation/i)).toBeNull();expect(screen.queryByText(/^Edit$/)).toBeNull();expect(screen.queryByText(/^Delete$/)).toBeNull()})
  it('renders a 404 and retryable non-404 error at the same identity',async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({code:'not_found',message:'No definition'}),{status:404})).mockResolvedValueOnce(new Response('{}',{status:500})).mockResolvedValueOnce(new Response(JSON.stringify(detail),{status:200}));vi.stubGlobal('fetch',fetchMock);const first=renderDetail();expect(await screen.findByText('Definition not found')).toBeTruthy();first.unmount();renderDetail();expect(await screen.findByText('Try again')).toBeTruthy();await userEvent.click(screen.getByText('Try again'));expect(await screen.findByText('Database Health')).toBeTruthy();expect(fetchMock.mock.calls[2][0]).toBe('/api/v1/observations/a')})
  it('backs to the definition list and aborts abandoned detail work',async()=>{let signal:AbortSignal|undefined;vi.stubGlobal('fetch',vi.fn((_url,init)=>{signal=(init as RequestInit).signal as AbortSignal;return new Promise(()=>{})}));const result=renderDetail();await waitFor(()=>expect(signal).toBeDefined());result.unmount();expect(signal?.aborted).toBe(true);vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify(detail),{status:200})));renderDetail();await userEvent.click(await screen.findByText('Back to Observations'));expect(await screen.findByText('Definition list')).toBeTruthy()})
  it('keeps the active detail when an abandoned route request resolves late',async()=>{const abandoned=deferred<Response>(),active=deferred<Response>();const fetchMock=vi.fn().mockReturnValueOnce(abandoned.promise).mockReturnValueOnce(active.promise);vi.stubGlobal('fetch',fetchMock);renderDetail();await userEvent.click(screen.getByText('Next definition'));active.resolve(new Response(JSON.stringify({...detail,id:'b',name:'Second definition'}),{status:200}));expect(await screen.findByText('Second definition')).toBeTruthy();abandoned.resolve(new Response(JSON.stringify({...detail,name:'Abandoned definition'}),{status:200}));await new Promise(resolve=>setTimeout(resolve));expect(screen.getByText('Second definition')).toBeTruthy();expect(screen.queryByText('Abandoned definition')).toBeNull();expect(fetchMock.mock.calls[1][0]).toBe('/api/v1/observations/b')})
  it('surfaces no stale error when an abandoned detail request fails late',async()=>{const abandoned=deferred<Response>(),active=deferred<Response>();vi.stubGlobal('fetch',vi.fn().mockReturnValueOnce(abandoned.promise).mockReturnValueOnce(active.promise));renderDetail();await userEvent.click(screen.getByText('Next definition'));active.resolve(new Response(JSON.stringify({...detail,id:'b',name:'Second definition'}),{status:200}));expect(await screen.findByText('Second definition')).toBeTruthy();abandoned.reject(new Error('late detail failure'));await new Promise(resolve=>setTimeout(resolve));expect(screen.queryByText(/Unable to load/)).toBeNull();expect(screen.getByText('Second definition')).toBeTruthy()})
})
