import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { ObservationsPage } from './ObservationsPage'

const definition={id:'a',name:'Database Health',description:'Database behavior',objective:'Observe only objective',schema_version:1,lenses:[{id:'metric-secret',name:'Metric secret',type:'metric',href:'/m'}],alert_lenses:[],relationships:[{id:'relationship-secret',name:'Relationship secret',href:'/r'}],href:'/a'}
function deferred<T>() { let resolve:(value:T)=>void;let reject:(reason?:unknown)=>void;const promise=new Promise<T>((res,rej)=>{resolve=res;reject=rej});return {promise,resolve:resolve!,reject:reject!} }
function renderPage() { return render(<MemoryRouter><Routes><Route path="*" element={<ObservationsPage/>}/><Route path="/observations/new" element={<p>Create seam</p>}/></Routes></MemoryRouter>) }
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals()})
describe('ObservationsPage',()=>{
  it('shows an explicit pending state then supported rows without runtime lifecycle controls',async()=>{const request=deferred<Response>();vi.stubGlobal('fetch',vi.fn().mockReturnValue(request.promise));renderPage();expect(screen.getByText('Loading definitions')).toBeTruthy();request.resolve(new Response(JSON.stringify([definition]),{status:200}));expect(await screen.findByText('Database Health')).toBeTruthy();expect(screen.getByText(/1 Metric lens/)).toBeTruthy();expect(screen.queryByText(/Latest run/i)).toBeNull();expect(screen.queryByText(/Analytical state/i)).toBeNull();expect(screen.queryByText(/^Edit$/)).toBeNull();expect(screen.queryByText(/^Delete$/)).toBeNull()})
  it('searches case-insensitive name and description only and clears a distinct no-match state',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify([definition]),{status:200})));renderPage();await screen.findByText('Database Health');const input=screen.getByLabelText('Search observations');await userEvent.type(input,'DATABASE');expect(screen.getByText('Database Health')).toBeTruthy();await userEvent.clear(input);await userEvent.type(input,'behavior');expect(screen.getByText('Database Health')).toBeTruthy();await userEvent.clear(input);await userEvent.type(input,'objective');expect(screen.getByText('No matching definitions')).toBeTruthy();expect(screen.queryByText('No Observation definitions yet')).toBeNull();await userEvent.click(screen.getByText('Clear search'));expect(screen.getByText('Database Health')).toBeTruthy();await userEvent.type(input,'metric-secret');expect(screen.getByText('No matching definitions')).toBeTruthy();await userEvent.clear(input);await userEvent.type(input,'relationship-secret');expect(screen.getByText('No matching definitions')).toBeTruthy()})
  it('shows a collection-empty state with an actionable create seam',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('[]',{status:200})));renderPage();expect(await screen.findByText('No Observation definitions yet')).toBeTruthy();const links=screen.getAllByRole('link',{name:'New Observation'});expect(links[links.length-1].getAttribute('href')).toBe('/observations/new');await userEvent.click(links[links.length-1]);expect(await screen.findByText('Create seam')).toBeTruthy()})
  it('makes the header primary action navigate to the create seam',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('[]',{status:200})));renderPage();await userEvent.click(await screen.findByRole('link',{name:'New Observation'}));expect(await screen.findByText('Create seam')).toBeTruthy()})
  it('shows a retryable list error',async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({code:'unavailable',message:'No connection'}),{status:503})).mockResolvedValueOnce(new Response('[]',{status:200}));vi.stubGlobal('fetch',fetchMock);renderPage();expect(await screen.findByRole('alert')).toBeTruthy();await userEvent.click(screen.getByText('Try again'));expect(await screen.findByText('No Observation definitions yet')).toBeTruthy();expect(fetchMock).toHaveBeenCalledTimes(2)})
  it('aborts a list request when its view unmounts',async()=>{let signal:AbortSignal|undefined;vi.stubGlobal('fetch',vi.fn((_url,init)=>{signal=(init as RequestInit).signal as AbortSignal;return new Promise(()=>{})}));const result=renderPage();await waitFor(()=>expect(signal).toBeDefined());result.unmount();expect(signal?.aborted).toBe(true)})
})
