import { ArrowLeft } from 'lucide-react'
import type { ReactNode } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { InlineNotice } from '../../components/ui'
import { getObservation } from './api'
import { useRequest } from './useRequest'

/** Renders the supported read-only configuration inspection route. */
export function ObservationDetailPage() {
  const {observationId=''}=useParams(),location=useLocation(),{state,retry}=useRequest(signal=>getObservation(observationId,signal),[observationId])
  const confirmation=location.state?.created?<div className="mb-5"><InlineNotice>Observation definition created successfully. You are viewing its read-only configuration.</InlineNotice></div>:null
  if(state.status==='loading')return <DetailFrame>{confirmation}<Panel title="Loading definition" detail="Retrieving the Observation definition…"/></DetailFrame>
  if(state.status==='error'){const notFound=(state.error as {status?:number}).status===404;return <DetailFrame>{confirmation}{notFound?<Panel title="Definition not found" detail="This Observation definition is unavailable or no longer exists."/>:<InlineNotice tone="error">Unable to load this Observation definition. <button className="font-semibold underline" onClick={retry}>Try again</button></InlineNotice>}</DetailFrame>}
  const observation=state.data
  return <DetailFrame>{confirmation}<header className="mb-8"><p className="text-sm text-[var(--color-text-secondary)]">Observation definition</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{observation.name}</h1>{observation.description?<p className="mt-3 max-w-3xl text-[var(--color-text-secondary)]">{observation.description}</p>:null}<p className="mt-4 text-sm"><span className="font-medium">Objective:</span> {observation.objective}</p></header><div className="grid gap-5 lg:grid-cols-2"><DefinitionGroup title="Metric lenses" empty="No Metric lenses configured." items={observation.lenses.map(lens=><><strong>{lens.name}</strong><br/><span>Metric: {lens.metric_id} · Unit: {lens.unit}</span><br/><span>References: {lens.reference_periods.join(', ')||'None'}</span></>)}/><DefinitionGroup title="Alert lenses" empty="No Alert lenses configured." items={observation.alert_lenses.map(lens=><><strong>{lens.name}</strong><br/><span>Source: {lens.source}</span><br/><span>References: {lens.reference_periods.join(', ')||'None'}</span></>)}/><DefinitionGroup title="Relationships" empty="No Relationships configured." items={observation.relationships.map(item=><><strong>{item.name}</strong><br/><span>Participants: {item.participants.join(', ')}</span></>)}/></div></DetailFrame>
}
function DetailFrame({children}:{children:ReactNode}) { return <section className="mx-auto max-w-6xl"><Link to="/observations" className="mb-7 inline-flex items-center gap-1 text-sm font-medium text-[var(--color-primary)] hover:underline"><ArrowLeft size={16} aria-hidden="true"/>Back to Observations</Link>{children}</section> }
function DefinitionGroup({title,empty,items}:{title:string;empty:string;items:ReactNode[]}) { return <section className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6"><h2 className="text-lg font-semibold">{title}</h2>{items.length===0?<p className="mt-3 text-sm text-[var(--color-text-secondary)]">{empty}</p>:<ul className="mt-4 space-y-3">{items.map((item,index)=><li key={index} className="rounded-lg border border-[var(--color-border)] p-3 text-sm text-[var(--color-text-secondary)]">{item}</li>)}</ul>}</section> }
function Panel({title,detail}:{title:string;detail:string}) { return <div className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] px-6 py-10 text-center"><h1 className="font-semibold">{title}</h1><p className="mt-2 text-sm text-[var(--color-text-secondary)]">{detail}</p></div> }
