import { cleanup, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import App from '../../App'
import { newAlert, newMetric, newRelationship, serializeDraft, validateRelationship, type DraftRelationship, type ObservationDraft } from './draft'
import { descriptorMapFromRows } from './RelationshipEditorPage'
import type { ObservationResponse } from './types'

const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status})
const capabilities={metric:[{adapter_type:'prometheus',sources:[{id:'primary',name:'Primary Prometheus'}]}]}
const observationId='f47ac10b-58cc-4c6f-91ae-1f8b50b65165'
const created:ObservationResponse={id:observationId,name:'Mixed topology',description:null,objective:'Observe related behavior',schema_version:1,lenses:[{id:'cpu',name:'CPU',type:'metric',href:`/api/v1/observations/${observationId}/lenses/cpu`,description:null,metric_id:'cpu_usage',adapter_type:'prometheus',source_id:'primary',query:'cpu_query',unit:'%',analysis_objectives:['spike'],reference_periods:[],observation_href:`/api/v1/observations/${observationId}`},{id:'throughput',name:'Throughput',type:'metric',href:`/api/v1/observations/${observationId}/lenses/throughput`,description:null,metric_id:'throughput',adapter_type:'prometheus',source_id:'primary',query:'throughput_query',unit:'rps',analysis_objectives:['drift'],reference_periods:[],observation_href:`/api/v1/observations/${observationId}`}],alert_lenses:[{id:'cpu',name:'CPU alert',type:'alert',href:`/api/v1/observations/${observationId}/alert-lenses/cpu`,description:null,source:'jira_track_and_release',selector:{query:'project=CPU'},analysis_objectives:[],reference_periods:[],observation_href:`/api/v1/observations/${observationId}`}],relationships:[{id:'cpu_throughput',name:'CPU and throughput',href:`/api/v1/observations/${observationId}/relationships/cpu_throughput`,description:null,participants:['cpu','throughput'],conditions:{cpu:{trend:{direction:'increasing'}}},expected:{throughput:{trend:{direction:'decreasing'}}},observation_href:`/api/v1/observations/${observationId}`}],href:`/api/v1/observations/${observationId}`}
const renderAt=(path='/observations/new')=>render(<MemoryRouter initialEntries={[path]}><App/></MemoryRouter>)
async function metric(user:ReturnType<typeof userEvent.setup>,id:string,name:string,unit='%'){await user.click(screen.getByText('Add Metric Lens'));await screen.findByRole('option',{name:'Primary Prometheus'});await user.type(screen.getByLabelText('Lens ID'),id);await user.type(screen.getByLabelText('Name'),name);await user.type(screen.getByLabelText('Metric ID'),`${id}_metric`);await user.type(screen.getByLabelText('Unit'),unit);await user.selectOptions(screen.getByLabelText('Metric source'),'primary');await user.type(screen.getByLabelText('Provider query'),`${id}_query`);await user.click(screen.getByLabelText('spike'));await user.click(screen.getByText('Apply changes'))}
async function alert(user:ReturnType<typeof userEvent.setup>){await user.click(screen.getByText('Add Alert Lens'));await user.type(screen.getByLabelText('Lens ID'),'cpu');await user.type(screen.getByLabelText('Name'),'CPU alert');await user.type(screen.getByLabelText('Provider selector'),'project=CPU');await user.click(screen.getByText('Apply changes'))}
async function relationship(user:ReturnType<typeof userEvent.setup>,conditional=true,id='cpu_throughput',name='CPU and throughput'){await user.click(screen.getByText('Add Relationship'));await user.type(screen.getByLabelText('Relationship ID'),id);await user.type(screen.getByLabelText('Name'),name);await user.click(screen.getByLabelText(/CPU \(cpu\)/));await user.click(screen.getByLabelText(/Throughput \(throughput\)/));if(conditional){await user.click(screen.getByText('+ Add condition'));const participants=screen.getAllByLabelText('When — conditions participant');await user.selectOptions(participants[0],'cpu');await user.selectOptions(screen.getAllByLabelText('When — conditions property')[0],'trend.direction');await user.selectOptions(screen.getAllByLabelText('When — conditions value')[0],'increasing')}await user.click(screen.getByText('+ Add expectation'));let participants=screen.getAllByLabelText('Expect — evaluated when applicable participant');await user.selectOptions(participants[0],'throughput');await user.selectOptions(screen.getAllByLabelText('Expect — evaluated when applicable property')[0],'trend.direction');await user.selectOptions(screen.getAllByLabelText('Expect — evaluated when applicable value')[0],'decreasing');if(!conditional){await user.click(screen.getByText('+ Add expectation'));participants=screen.getAllByLabelText('Expect — evaluated when applicable participant');await user.selectOptions(participants[1],'cpu')}await user.click(screen.getByText('Apply changes'))}
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals()})

describe('Relationship draft contracts',()=>{
  it('maps only the accepted nested vocabulary conjunctively and rejects duplicate, unknown, Alert-only, and unused participants',()=>{const cpu={...newMetric('metric-cpu'),id:'cpu',name:'CPU',metric_id:'cpu',source_id:'primary',query:'cpu',unit:'%',analysis_objectives:[],reference_periods:[]},throughput={...newMetric('metric-throughput'),id:'throughput',name:'Throughput',metric_id:'throughput',source_id:'primary',query:'throughput',unit:'rps',analysis_objectives:[],reference_periods:[]},relation={...newRelationship('relationship'),id:'cpu_throughput',name:'CPU and throughput',participants:['cpu','throughput'],conditions:{cpu:{trend:{direction:'increasing'},variability:{state:'low'}}},expected:{throughput:{trend:{direction:'decreasing',rate:'fast'}}}} as DraftRelationship;expect(validateRelationship(relation,[cpu,throughput])).toEqual({});expect(descriptorMapFromRows([{key:'a',lensId:'cpu',property:'trend.direction',value:'increasing'},{key:'b',lensId:'cpu',property:'variability.state',value:'low'}])).toEqual({cpu:{trend:{direction:'increasing'},variability:{state:'low'}}});expect(validateRelationship({...relation,participants:['cpu','cpu']},[cpu,throughput]).participants).toMatch(/distinct/);expect(validateRelationship({...relation,participants:['cpu','alert_only'],expected:{alert_only:{trend:{direction:'decreasing'}}}},[cpu,throughput]).participants).toMatch(/Metric/);expect(validateRelationship({...relation,participants:['cpu','throughput'],expected:{cpu:{trend:{direction:'decreasing'}}}},[cpu,throughput]).topology).toMatch(/Every participant/);expect(validateRelationship({...relation,expected:{throughput:{trend:{direction:'unknown' as never}}}},[cpu,throughput]).descriptors).toMatch(/supported/)} )
  it('serializes ordered Relationship children without client keys and permits a same-ID Alert only when a Metric Lens exists',()=>{const cpu={...newMetric('metric-cpu'),id:'cpu',name:'CPU',metric_id:'cpu',source_id:'primary',query:'cpu',unit:'%',analysis_objectives:[],reference_periods:[]},relation={...newRelationship('relationship'),id:'cpu_throughput',name:'CPU behavior',participants:['cpu','throughput'],conditions:{},expected:{cpu:{trend:{direction:'increasing'}},throughput:{variability:{state:'low'}}}} as DraftRelationship,throughput={...newMetric('metric-throughput'),id:'throughput',name:'Throughput',metric_id:'throughput',source_id:'primary',query:'throughput',unit:'rps',analysis_objectives:[],reference_periods:[]},draft:ObservationDraft={name:'Mixed',description:'',objective:'Observe',lenses:[cpu,throughput],alert_lenses:[{...newAlert('alert'),id:'cpu',name:'CPU alert',selector:{query:'project=CPU'}}],relationships:[relation]};expect(validateRelationship(relation,draft.lenses,draft.relationships)).toEqual({});expect(serializeDraft(draft).relationships).toEqual([{id:'cpu_throughput',name:'CPU behavior',description:null,participants:['cpu','throughput'],conditions:{},expected:{cpu:{trend:{direction:'increasing'}},throughput:{variability:{state:'low'}}}}])})
})

describe('Relationship editor',()=>{
  it('applies conditional and always-applicable relationships locally, keeps opaque key/order on edit, and never writes',async()=>{const user=userEvent.setup(),fetchMock=vi.fn().mockResolvedValue(response(capabilities));vi.stubGlobal('fetch',fetchMock);renderAt();await metric(user,'cpu','CPU');await metric(user,'throughput','Throughput','rps');await relationship(user,true);await relationship(user,false,'cpu_throughput_always','Always applicable');const cards=()=>Array.from(screen.getByRole('heading',{name:'Relationships'}).parentElement!.querySelectorAll('p')).filter(item=>item.querySelector('a'));const href=cards()[0].querySelector('a')?.getAttribute('href');expect(cards().map(card=>card.childNodes[0].textContent?.trim())).toEqual(['CPU and throughput','Always applicable']);await user.click(cards()[0].querySelector('a')!);await user.clear(screen.getByLabelText('Name'));await user.type(screen.getByLabelText('Name'),'Updated relationship');await user.click(screen.getByText('Apply changes'));expect(cards()[0].textContent).toContain('Updated relationship');expect(cards()[0].querySelector('a')?.getAttribute('href')).toBe(href);expect(fetchMock.mock.calls.filter(([,init])=>(init as RequestInit|undefined)?.method==='POST')).toEqual([])})
  it('cancels local Relationship changes without a draft mutation or a write',async()=>{const user=userEvent.setup(),fetchMock=vi.fn().mockResolvedValue(response(capabilities));vi.stubGlobal('fetch',fetchMock);renderAt();await metric(user,'cpu','CPU');await metric(user,'throughput','Throughput');await relationship(user,true);await user.click(screen.getByRole('heading',{name:'Relationships'}).parentElement!.querySelector('a')!);await user.clear(screen.getByLabelText('Name'));await user.type(screen.getByLabelText('Name'),'Discarded');await user.click(screen.getByText('Cancel'));expect(screen.queryByText('Discarded')).toBeNull();expect(fetchMock.mock.calls.filter(([,init])=>(init as RequestInit|undefined)?.method==='POST')).toEqual([])})
  it('posts exactly one complete mixed aggregate, corrects retained Relationship data, then retries successfully',async()=>{const user=userEvent.setup();let posts=0;const fetchMock=vi.fn().mockImplementation((url:string,init?:RequestInit)=>url==='/api/v1/observation-definition-capabilities'?Promise.resolve(response(capabilities)):url==='/api/v1/observations'&&init?.method==='POST'?Promise.resolve(++posts===1?response({code:'validation_error',message:'Correct Relationship rule',field:'relationships.0.expected'},422):response(created,201)):Promise.resolve(response(created)));vi.stubGlobal('fetch',fetchMock);renderAt();await user.type(await screen.findByLabelText('Name'),'Mixed topology');await user.type(screen.getByLabelText('Objective'),'Observe related behavior');await metric(user,'cpu','CPU');await metric(user,'throughput','Throughput','rps');await alert(user);await relationship(user,true);await user.click(screen.getAllByRole('button',{name:'Create Observation'})[0]);expect((await screen.findByRole('alert')).textContent).toContain('Correct Relationship rule');await user.click(screen.getByText('Correct Relationship'));expect((screen.getByLabelText('Relationship ID') as HTMLInputElement).value).toBe('cpu_throughput');expect((screen.getByLabelText('Name') as HTMLInputElement).value).toBe('CPU and throughput');expect((screen.getByLabelText('CPU (cpu)') as HTMLInputElement).checked).toBe(true);expect((screen.getByLabelText('Throughput (throughput)') as HTMLInputElement).checked).toBe(true);expect((screen.getByLabelText('When — conditions value') as HTMLSelectElement).value).toBe('increasing');expect((screen.getByLabelText('Expect — evaluated when applicable value') as HTMLSelectElement).value).toBe('decreasing');await user.selectOptions(screen.getByLabelText('Expect — evaluated when applicable value'),'stable');await user.click(screen.getByText('Apply changes'));await user.click(screen.getAllByRole('button',{name:'Create Observation'})[0]);expect(await screen.findByText(/created successfully/i)).toBeTruthy();const calls=fetchMock.mock.calls.filter(([url,init])=>url==='/api/v1/observations'&&(init as RequestInit).method==='POST');expect(calls).toHaveLength(2);const first=JSON.parse(String((calls[0][1] as RequestInit).body)),second=JSON.parse(String((calls[1][1] as RequestInit).body));expect(first.relationships[0].expected.throughput.trend.direction).toBe('decreasing');expect(second).toEqual({...first,relationships:[{...first.relationships[0],expected:{throughput:{trend:{direction:'stable'}}}}]});expect(fetchMock.mock.calls.filter(([url])=>String(url).includes('/lenses/')||String(url).includes('preflight'))).toEqual([])})
})
